/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@papp@sviews@ssite_shell.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@papp@sviews@ssite_shell.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZparsecfg_u356)(NimStringV2* result_p0, NimStringV2 value_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[151+1];
} TM__V0qbsqRreLaxnB7Cp9bCAPA_2 = { 151 | NIM_STRLIT_FLAG, "<!DOCTYPE html>\012<html lang=\"ja\">\012<head>\012  <meta charset=\"UTF-8\" />\012  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\012  <title>" };
static const NimStringV2 TM__V0qbsqRreLaxnB7Cp9bCAPA_3 = {151, (NimStrPayload*)&TM__V0qbsqRreLaxnB7Cp9bCAPA_2};
static const struct {
  NI cap; NIM_CHAR data[363+1];
} TM__V0qbsqRreLaxnB7Cp9bCAPA_4 = { 363 | NIM_STRLIT_FLAG, "</title>\012  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\012  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\012  <link href=\"https://fonts.googleapis.com/css2\?family=Inter:wght@300;400;600;800&amp;family=Outfit:wght@400;700&amp;display=swap\" rel=\"stylesheet\" />\012  <link rel=\"stylesheet\" href=\"/css/styles.css\" />\012</head>\012<body>\012" };
static const NimStringV2 TM__V0qbsqRreLaxnB7Cp9bCAPA_5 = {363, (NimStrPayload*)&TM__V0qbsqRreLaxnB7Cp9bCAPA_4};
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__V0qbsqRreLaxnB7Cp9bCAPA_6 = { 60 | NIM_STRLIT_FLAG, "\012<script src=\"/js/script.js\" defer></script>\012</body>\012</html>" };
static const NimStringV2 TM__V0qbsqRreLaxnB7Cp9bCAPA_7 = {60, (NimStrPayload*)&TM__V0qbsqRreLaxnB7Cp9bCAPA_6};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, siteShell__OOZsrcZappZviewsZsite95shell_u2)(NimStringV2 title_p0, NimStringV2 mainInner_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("siteShell", "/Users/nakagawa_shota/repo/valit/tiara/website/src/app/views/site_shell.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		NimStringV2 fmtRes_1;
		fmtRes_1.len = 0; fmtRes_1.p = NIM_NIL;
		nimlf_(653, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strformat.nim");		nimlf_(4, "/Users/nakagawa_shota/repo/valit/tiara/website/src/app/views/site_shell.nim");		fmtRes_1 = rawNewString(((NI)612));
		prepareAdd((&fmtRes_1), 151);
appendString((&fmtRes_1), TM__V0qbsqRreLaxnB7Cp9bCAPA_3);
		formatValue__pureZparsecfg_u356((&fmtRes_1), title_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		prepareAdd((&fmtRes_1), 363);
appendString((&fmtRes_1), TM__V0qbsqRreLaxnB7Cp9bCAPA_5);
		formatValue__pureZparsecfg_u356((&fmtRes_1), mainInner_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		prepareAdd((&fmtRes_1), 60);
appendString((&fmtRes_1), TM__V0qbsqRreLaxnB7Cp9bCAPA_7);
		nimlf_(653, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strformat.nim");		result = fmtRes_1;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
