/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@papp@scomponents@spage.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@papp@scomponents@spage.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w;
typedef struct tyObject_RequestcolonObjectType___8b9a0rcGIyx3NkK29a9c6kKhw tyObject_RequestcolonObjectType___8b9a0rcGIyx3NkK29a9c6kKhw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w {
	NI status;
	NimStringV2 body;
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers;
};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderCatalogDocument__OOZOOZexamplesZpreview_u569)(NimStringV2 title_p0, NimStringV2 clientScriptSrc_p1, NimStringV2 homeHref_p2, NimStringV2 docsHref_p3, NimStringV2 componentsHref_p4);
N_LIB_PRIVATE N_NIMCALL(tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w*, disableLayout__pkgZcrownZcore_u276)(tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w* res_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w*, htmlResponse__pkgZcrownZcore_u232)(NimStringV2 content_p0, NI status_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZbasolatoZcoreZresponse_u66)(tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__0kAvTGtSeIstDYgID47GEg_2 = { 34 | NIM_STRLIT_FLAG, "Tiara Lab \342\200\224 Component Playground" };
static const NimStringV2 TM__0kAvTGtSeIstDYgID47GEg_3 = {34, (NimStrPayload*)&TM__0kAvTGtSeIstDYgID47GEg_2};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__0kAvTGtSeIstDYgID47GEg_4 = { 13 | NIM_STRLIT_FLAG, "/tiara_client" };
static const NimStringV2 TM__0kAvTGtSeIstDYgID47GEg_5 = {13, (NimStrPayload*)&TM__0kAvTGtSeIstDYgID47GEg_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__0kAvTGtSeIstDYgID47GEg_6 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__0kAvTGtSeIstDYgID47GEg_7 = {1, (NimStrPayload*)&TM__0kAvTGtSeIstDYgID47GEg_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__0kAvTGtSeIstDYgID47GEg_8 = { 5 | NIM_STRLIT_FLAG, "/docs" };
static const NimStringV2 TM__0kAvTGtSeIstDYgID47GEg_9 = {5, (NimStrPayload*)&TM__0kAvTGtSeIstDYgID47GEg_8};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__0kAvTGtSeIstDYgID47GEg_10 = { 11 | NIM_STRLIT_FLAG, "/components" };
static const NimStringV2 TM__0kAvTGtSeIstDYgID47GEg_11 = {11, (NimStrPayload*)&TM__0kAvTGtSeIstDYgID47GEg_10};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w*, page__OOZsrcZappZcomponentsZpage_u3)(tyObject_RequestcolonObjectType___8b9a0rcGIyx3NkK29a9c6kKhw* req_p0) {
	tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w* result;
	NimStringV2 html_1;
	tyObject_ResponsecolonObjectType___8XWyPBOjXJkQdxDG9a5At6w* colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("page", "/Users/nakagawa_shota/repo/valit/tiara/website/src/app/components/page.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	html_1.len = 0; html_1.p = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(5, "/Users/nakagawa_shota/repo/valit/tiara/website/src/app/components/page.nim");	html_1 = renderCatalogDocument__OOZOOZexamplesZpreview_u569(TM__0kAvTGtSeIstDYgID47GEg_3, TM__0kAvTGtSeIstDYgID47GEg_5, TM__0kAvTGtSeIstDYgID47GEg_7, TM__0kAvTGtSeIstDYgID47GEg_9, TM__0kAvTGtSeIstDYgID47GEg_11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(4);	nimln_(12);	colontmpD_ = htmlResponse__pkgZcrownZcore_u232(html_1, ((NI)200));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = disableLayout__pkgZcrownZcore_u276(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(31, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.15.0-6ef054fa959d4a10421723c5ccbd3ea9b751c240/basolato/core/response.nim");	eqdestroy___pkgZbasolatoZcoreZresponse_u66(colontmpD_);
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (html_1.p && !(html_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(html_1.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
