/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pbasolato@score@sbaseEnv.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pbasolato@score@sbaseEnv.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <dirent.h>
#include <sys/types.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__rEQnODVBLiWR7M1Ckl1lOg tyTuple__rEQnODVBLiWR7M1Ckl1lOg;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__IWVof32nvF9bSVI9atrGkyDw tyTuple__IWVof32nvF9bSVI9atrGkyDw;
typedef struct tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA;
typedef struct tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg;
typedef struct tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg;
typedef struct tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg;
typedef struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA;
typedef struct tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw;
struct tyTuple__rEQnODVBLiWR7M1Ckl1lOg {
	tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw Field0;
	NimStringV2 Field1;
};
typedef NIM_CHAR tyArray__bErjiHmvISNmC2iIqkq21Q[256];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyTuple__IWVof32nvF9bSVI9atrGkyDw {
	tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw Field0;
	NIM_BOOL Field1;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA {
	RootObj Sup;
	NI bufpos;
	NimStringV2 buf;
	tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__7nmFzAY8WAArf5RvWTtaQA;
struct tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg {
	tyEnum_TokKind__7nmFzAY8WAArf5RvWTtaQA kind;
	NimStringV2 literal;
};
struct tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg {
	tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA Sup;
	tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg tok;
	NimStringV2 filename;
};
typedef N_NIMCALL_PTR(void, tyProc__Xl32m0kTaH9ahJZb5rqVy6w) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ooJWa8lnlfnobNqxEOtnNA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__E19bfDo0XX9btMFiY2C0tGGg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qvufjYFbEQ9cqXk4e8pAzJQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__wBfXfmCdEwRLtDI7TCPoAQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ohJ27oJZLprJ3hzTGNCkpA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qcX1k0ZWyDvPcQjruoqTPg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__E6HHS1dkEvJbg7JG3Yyt9ag) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg {
	RootObj Sup;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w closeImpl;
	tyProc__ooJWa8lnlfnobNqxEOtnNA atEndImpl;
	tyProc__E19bfDo0XX9btMFiY2C0tGGg setPositionImpl;
	tyProc__qvufjYFbEQ9cqXk4e8pAzJQ getPositionImpl;
	tyProc__wBfXfmCdEwRLtDI7TCPoAQ readDataStrImpl;
	tyProc__ohJ27oJZLprJ3hzTGNCkpA readLineImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg readDataImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg peekDataImpl;
	tyProc__E6HHS1dkEvJbg7JG3Yyt9ag writeDataImpl;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w flushImpl;
};
struct tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA {
	tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg Sup;
	FILE* f;
};
typedef NU8 tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA;
typedef NimStringV2 tyArray__dyW7vpmfeTYw8kX3EXuaJA[3];
typedef NU8 tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw;
struct tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ {
	RootObj Sup;
	tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw kind;
union{
	struct {
	NimStringV2 section;
} _kind_2;
	struct {
	NimStringV2 key;
	NimStringV2 value;
} _kind_3;
	struct {
	NimStringV2 msg;
} _kind_4;
};
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA {
	NI a;
	NI b;
};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__IWVof32nvF9bSVI9atrGkyDw, getSymlinkFileKind__stdZprivateZoscommon_u17)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5635)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZprivateZosdirs_u277)(tyTuple__rEQnODVBLiWR7M1Ckl1lOg* dest_p0, tyTuple__rEQnODVBLiWR7M1Ckl1lOg src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2722)(NimStringV2* dest_p0);
static N_INLINE(NimStringV2, X5BX5D___pkgZbasolatoZcoreZbase69nv_u13)(NimStringV2* s_p0, NI s_p0Len_0, NI i_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*, newFileStream__pureZstreams_u1210)(NimStringV2 filename_p0, tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA mode_p1, NI bufSize_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u1093)(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg* c_p0, tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* input_p1, NimStringV2 filename_p2, NI lineOffset_p3);
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg* c_p0, tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u463)(tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, putEnv__stdZenvvars_u23)(NimStringV2 key_p0, NimStringV2 val_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZparsecfg_u22)(tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u62)(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosdirs_u268)(tyTuple__rEQnODVBLiWR7M1Ckl1lOg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseBool__pureZstrutils_u1113)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IUoffNuVge7huBUi8pG6JA_2 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_3 = {1, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__IUoffNuVge7huBUi8pG6JA_4 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_5 = {2, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IUoffNuVge7huBUi8pG6JA_7 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_8 = {1, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_7};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__IUoffNuVge7huBUi8pG6JA_9 = { 4 | NIM_STRLIT_FLAG, ".env" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_10 = {4, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_9};
extern TNimTypeV2 NTIv2__xKGlcBiu2pA13Poy9c49b9ayg_;
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_11 = {4, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_9};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__IUoffNuVge7huBUi8pG6JA_12 = { 27 | NIM_STRLIT_FLAG, "Basolato uses config file \'" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_13 = {27, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IUoffNuVge7huBUi8pG6JA_14 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_15 = {1, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_14};
extern TNimTypeV2 NTIv2__xinZeGTaQCxxN1TGrWYliQ_;
static const struct {
  NI cap; NIM_CHAR data[64+1];
} TM__IUoffNuVge7huBUi8pG6JA_16 = { 64 | NIM_STRLIT_FLAG, "field \'key\' is not accessible for type \'CfgEvent\' using \'kind = " };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_17 = {64, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_16};
static const struct {
  NI cap; NIM_CHAR data[66+1];
} TM__IUoffNuVge7huBUi8pG6JA_18 = { 66 | NIM_STRLIT_FLAG, "field \'value\' is not accessible for type \'CfgEvent\' using \'kind = " };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_19 = {66, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_18};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__IUoffNuVge7huBUi8pG6JA_20 = { 10 | NIM_STRLIT_FLAG, "SECRET_KEY" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_21 = {10, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_20};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__IUoffNuVge7huBUi8pG6JA_22 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_23 = {0, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_22};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__IUoffNuVge7huBUi8pG6JA_24 = { 14 | NIM_STRLIT_FLAG, "LOG_IS_DISPLAY" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_25 = {14, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_24};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__IUoffNuVge7huBUi8pG6JA_26 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_27 = {4, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_26};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__IUoffNuVge7huBUi8pG6JA_28 = { 11 | NIM_STRLIT_FLAG, "LOG_IS_FILE" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_29 = {11, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_28};
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_30 = {4, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_26};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__IUoffNuVge7huBUi8pG6JA_31 = { 17 | NIM_STRLIT_FLAG, "LOG_IS_ERROR_FILE" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_32 = {17, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_31};
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_33 = {4, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_26};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__IUoffNuVge7huBUi8pG6JA_34 = { 7 | NIM_STRLIT_FLAG, "LOG_DIR" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_35 = {7, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_34};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__IUoffNuVge7huBUi8pG6JA_36 = { 4 | NIM_STRLIT_FLAG, "logs" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_37 = {4, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_36};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__IUoffNuVge7huBUi8pG6JA_38 = { 12 | NIM_STRLIT_FLAG, "SESSION_TIME" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_39 = {12, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_38};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__IUoffNuVge7huBUi8pG6JA_40 = { 5 | NIM_STRLIT_FLAG, "20160" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_41 = {5, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_40};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__IUoffNuVge7huBUi8pG6JA_42 = { 14 | NIM_STRLIT_FLAG, "COOKIE_DOMAINS" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_43 = {14, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_42};
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_44 = {0, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_22};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__IUoffNuVge7huBUi8pG6JA_45 = { 23 | NIM_STRLIT_FLAG, "ENABLE_ANONYMOUS_COOKIE" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_46 = {23, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_45};
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_47 = {4, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_26};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__IUoffNuVge7huBUi8pG6JA_48 = { 6 | NIM_STRLIT_FLAG, "LOCALE" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_49 = {6, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_48};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__IUoffNuVge7huBUi8pG6JA_50 = { 2 | NIM_STRLIT_FLAG, "en" };
static const NimStringV2 TM__IUoffNuVge7huBUi8pG6JA_51 = {2, (NimStrPayload*)&TM__IUoffNuVge7huBUi8pG6JA_50};
N_LIB_PRIVATE NimStringV2 SECRET_KEY__pkgZbasolatoZcoreZbase69nv_u25;
N_LIB_PRIVATE NimStringV2 LOG_DIR__pkgZbasolatoZcoreZbase69nv_u29;
N_LIB_PRIVATE NimStringV2 COOKIE_DOMAINS__pkgZbasolatoZcoreZbase69nv_u31;
N_LIB_PRIVATE NimStringV2 LOCALE__pkgZbasolatoZcoreZbase69nv_u33;
N_LIB_PRIVATE tyTuple__rEQnODVBLiWR7M1Ckl1lOg f__pkgZbasolatoZcoreZbase69nv_u12;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
N_LIB_PRIVATE NimStringV2 path__pkgZbasolatoZcoreZbase69nv_u64;
N_LIB_PRIVATE tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* f__pkgZbasolatoZcoreZbase69nv_u65;
N_LIB_PRIVATE tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg p__pkgZbasolatoZcoreZbase69nv_u66;
N_LIB_PRIVATE tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ e__pkgZbasolatoZcoreZbase69nv_u67;
N_LIB_PRIVATE NIM_BOOL IS_DISPLAY__pkgZbasolatoZcoreZbase69nv_u26;
N_LIB_PRIVATE NIM_BOOL IS_FILE__pkgZbasolatoZcoreZbase69nv_u27;
N_LIB_PRIVATE NIM_BOOL IS_ERROR_FILE__pkgZbasolatoZcoreZbase69nv_u28;
N_LIB_PRIVATE NI SESSION_TIME__pkgZbasolatoZcoreZbase69nv_u30;
N_LIB_PRIVATE NIM_BOOL ENABLE_ANONYMOUS_COOKIE__pkgZbasolatoZcoreZbase69nv_u32;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");
{	nimlf_(33, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(178, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	result = nosjoinPath(head_p0, tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NimStringV2, X5BX5D___pkgZbasolatoZcoreZbase69nv_u13)(NimStringV2* s_p0, NI s_p0Len_0, NI i_p1) {
	NimStringV2 result;
	NI TM__IUoffNuVge7huBUi8pG6JA_6;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/indices.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	nimlf_(23, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/indices.nim");	if (nimSubInt(s_p0Len_0, i_p1, &TM__IUoffNuVge7huBUi8pG6JA_6)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IUoffNuVge7huBUi8pG6JA_6) < 0 || (NI)(TM__IUoffNuVge7huBUi8pG6JA_6) >= s_p0Len_0){ raiseIndexError2((NI)(TM__IUoffNuVge7huBUi8pG6JA_6),s_p0Len_0-1); goto BeforeRet_;
	}
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqcopy___system_u2725((&result), s_p0[(NI)(TM__IUoffNuVge7huBUi8pG6JA_6)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atpbasolatoatscoreatsbaseEnvdotnim_Init000)(void) {
{
	TFrame FR_; FR_.len = 0;
	p__pkgZbasolatoZcoreZbase69nv_u66.Sup.Sup.m_type = (&NTIv2__xKGlcBiu2pA13Poy9c49b9ayg_);
	e__pkgZbasolatoZcoreZbase69nv_u67.Sup.m_type = (&NTIv2__xinZeGTaQCxxN1TGrWYliQ_);
}/* preInitProc end */
{
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	NimStringV2 colontmpD__5;
	NimStringV2 colontmpD__6;
	NimStringV2 colontmpD__7;
	NimStringV2 T105_;
	NIM_BOOL T106_;
	NIM_BOOL T107_;
	NIM_BOOL T108_;
	NimStringV2 T109_;
	NI T110_;
	NimStringV2 T111_;
	NIM_BOOL T112_;
	NimStringV2 T113_;
NIM_BOOL* nimErr_;
	nimfr_("baseEnv", "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.15.0-6ef054fa959d4a10421723c5ccbd3ea9b751c240/basolato/core/baseEnv.nim");
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
	{
		NimStringV2 colontmp_;
		DIR* d_1;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		nimlf_(154, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");		nimlf_(14, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.15.0-6ef054fa959d4a10421723c5ccbd3ea9b751c240/basolato/core/baseEnv.nim");		colontmp_ = nosgetCurrentDir();
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		nimlf_(222, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");		d_1 = opendir(nimToCStringConv(colontmp_));
		nimln_(223);		{
			if (!(d_1 == ((DIR*) NIM_NIL))) goto LA6_;
			nimln_(224);			{
				NI32 T12_;
				if (!NIM_FALSE) goto LA10_;
				nimln_(225);				T12_ = (NI32)0;
				T12_ = osLastError__stdZoserrors_u122();
				if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
				raiseOSError__stdZoserrors_u119(T12_, colontmp_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			}
LA10_: ;
		}
		goto LA4_;
LA6_: ;
		{
			{
				nimln_(228);				while (1) {
					{
						NimStringV2 y_1;
						struct dirent* x_1;
						y_1.len = 0; y_1.p = NIM_NIL;
						nimln_(229);						x_1 = readdir(d_1);
						nimln_(230);						{
							if (!(x_1 == ((struct dirent*) NIM_NIL))) goto LA21_;
							nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");							if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
							nimlf_(230, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");							goto LA15;
						}
LA21_: ;
						nimln_(231);						y_1 = cstrToNimstr(((NCSTRING) ((*x_1).d_name)));
						nimln_(232);						{
							NIM_BOOL T25_;
							NimStringV2 path_1;
							tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__8;
							NimStringV2 colontmpD__9;
							struct stat s_1;
							tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw k_1;
							tyTuple__rEQnODVBLiWR7M1Ckl1lOg T76_;
							NimStringV2 blitTmp_1;
							T25_ = (NIM_BOOL)0;
							T25_ = !(eqStrings(y_1, TM__IUoffNuVge7huBUi8pG6JA_3));
							if (!(T25_)) goto LA26_;
							T25_ = !(eqStrings(y_1, TM__IUoffNuVge7huBUi8pG6JA_5));
LA26_: ;
							if (!T25_) goto LA27_;
							path_1.len = 0; path_1.p = NIM_NIL;
							colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
							colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
							nimZeroMem((void*)(&s_1), sizeof(struct stat));
							nimln_(234);							path_1 = slash___stdZprivateZospaths2_u88(colontmp_, y_1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
							nimln_(235);							{
								if (!NIM_TRUE) goto LA32_;
								nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");								eqcopy___system_u2725((&y_1), path_1);
							}
LA32_: ;
							nimlf_(237, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");							k_1 = ((tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw)0);
							nimln_(254);							switch ((*x_1).d_type) {
							case ((NI8)4):
							{
								nimln_(255);								k_1 = ((tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw)2);
							}
							break;
							case ((NI8)10):
							{
								NIM_BOOL isSpecialX60gensym19__1;
								tyTuple__IWVof32nvF9bSVI9atrGkyDw tmpTupleAsgn;
								isSpecialX60gensym19__1 = (NIM_BOOL)0;
								nimln_(241);								tmpTupleAsgn = getSymlinkFileKind__stdZprivateZoscommon_u17(path_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
								k_1 = tmpTupleAsgn.Field0;
								isSpecialX60gensym19__1 = tmpTupleAsgn.Field1;
								nimln_(257);								{
									NIM_BOOL T38_;
									nimln_(242);									T38_ = (NIM_BOOL)0;
									T38_ = NIM_FALSE;
									if (!(T38_)) goto LA39_;
									T38_ = isSpecialX60gensym19__1;
LA39_: ;
									if (!T38_) goto LA40_;
									nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");									if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
									nimln_(2219);									eqdestroy___system_u5635(colontmpD__8);
									nimln_(394);									if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
									if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
									nimlf_(242, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");									goto LA17;
								}
LA40_: ;
							}
							break;
							case ((NI8)0):
							{
								nimln_(259);								{
									int T45_;
									nimln_(245);									T45_ = (int)0;
									T45_ = lstat(nimToCStringConv(path_1), (&s_1));
									if (!(T45_ < ((NI32)0))) goto LA46_;
									nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");									if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
									nimln_(2219);									eqdestroy___system_u5635(colontmpD__8);
									nimln_(394);									if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
									if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
									nimlf_(245, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");									goto LA17;
								}
								goto LA43_;
LA46_: ;
								{
									NIM_BOOL T49_;
									nimln_(246);									T49_ = (NIM_BOOL)0;
									T49_ = S_ISDIR(s_1.st_mode);
									if (!T49_) goto LA50_;
									nimln_(247);									k_1 = ((tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw)2);
								}
								goto LA43_;
LA50_: ;
								{
									NIM_BOOL T53_;
									NIM_BOOL isSpecialX60gensym21__1;
									tyTuple__IWVof32nvF9bSVI9atrGkyDw tmpTupleAsgn_2;
									nimln_(248);									T53_ = (NIM_BOOL)0;
									T53_ = S_ISLNK(s_1.st_mode);
									if (!T53_) goto LA54_;
									isSpecialX60gensym21__1 = (NIM_BOOL)0;
									nimln_(241);									tmpTupleAsgn_2 = getSymlinkFileKind__stdZprivateZoscommon_u17(path_1);
									if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
									k_1 = tmpTupleAsgn_2.Field0;
									isSpecialX60gensym21__1 = tmpTupleAsgn_2.Field1;
									nimln_(249);									{
										NIM_BOOL T58_;
										nimln_(242);										T58_ = (NIM_BOOL)0;
										T58_ = NIM_FALSE;
										if (!(T58_)) goto LA59_;
										T58_ = isSpecialX60gensym21__1;
LA59_: ;
										if (!T58_) goto LA60_;
										nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");										if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
										nimln_(2219);										eqdestroy___system_u5635(colontmpD__8);
										nimln_(394);										if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
										if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
										nimlf_(242, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");										goto LA17;
									}
LA60_: ;
								}
								goto LA43_;
LA54_: ;
								{
									NIM_BOOL T63_;
									NIM_BOOL T65_;
									nimln_(250);									T63_ = (NIM_BOOL)0;
									T63_ = NIM_FALSE;
									if (!(T63_)) goto LA64_;
									T65_ = (NIM_BOOL)0;
									T65_ = S_ISREG(s_1.st_mode);
									T63_ = !(T65_);
LA64_: ;
									if (!T63_) goto LA66_;
									nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");									if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
									nimln_(2219);									eqdestroy___system_u5635(colontmpD__8);
									nimln_(394);									if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
									if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
									nimlf_(250, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");									goto LA17;
								}
								goto LA43_;
LA66_: ;
LA43_: ;
							}
							break;
							default:
							{
								nimln_(261);								{
									NIM_BOOL T71_;
									T71_ = (NIM_BOOL)0;
									T71_ = NIM_FALSE;
									if (!(T71_)) goto LA72_;
									T71_ = !(((*x_1).d_type == ((NI8)8)));
LA72_: ;
									if (!T71_) goto LA73_;
									nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");									if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
									nimln_(2219);									eqdestroy___system_u5635(colontmpD__8);
									nimln_(394);									if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
									if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
									nimlf_(261, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");									goto LA17;
								}
								goto LA69_;
LA73_: ;
								{
								}
LA69_: ;
							}
							break;
							}
							nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");							T76_.Field0 = k_1;
							nimlf_(266, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");							blitTmp_1 = y_1;
							nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");							eqwasMoved___system_u2722((&y_1));
							T76_.Field1 = blitTmp_1;
							nimln_(934);							eqsink___stdZprivateZosdirs_u277((&f__pkgZbasolatoZcoreZbase69nv_u12), T76_);
							nimlf_(15, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.15.0-6ef054fa959d4a10421723c5ccbd3ea9b751c240/basolato/core/baseEnv.nim");							{
								NimStringV2 colontmpD__10;
								NimStringV2 T82_;
								tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* T83_;
								tyArray__dyW7vpmfeTYw8kX3EXuaJA T84_;
								int T93_;
								colontmpD__8 = nsuSplitString(f__pkgZbasolatoZcoreZbase69nv_u12.Field1, TM__IUoffNuVge7huBUi8pG6JA_8, ((NI)-1));
								if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
								colontmpD__9 = X5BX5D___pkgZbasolatoZcoreZbase69nv_u13(((colontmpD__8).p) ? (colontmpD__8.p->data) : NIM_NIL, colontmpD__8.len, ((NI)1));
								if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
								if (!eqStrings(colontmpD__9, TM__IUoffNuVge7huBUi8pG6JA_10)) goto LA79_;
								path__pkgZbasolatoZcoreZbase69nv_u64.len = 0; path__pkgZbasolatoZcoreZbase69nv_u64.p = NIM_NIL;
								colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
								f__pkgZbasolatoZcoreZbase69nv_u65 = 0;
								nimZeroMem((void*)(&p__pkgZbasolatoZcoreZbase69nv_u66), sizeof(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg));
								p__pkgZbasolatoZcoreZbase69nv_u66.Sup.Sup.m_type = (&NTIv2__xKGlcBiu2pA13Poy9c49b9ayg_);
								nimln_(16);								colontmpD__10 = nosgetCurrentDir();
								if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
								T82_.len = 0; T82_.p = NIM_NIL;
								T82_ = slash___stdZprivateZospaths2_u88(colontmpD__10, TM__IUoffNuVge7huBUi8pG6JA_11);
								if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T82_); goto LA81_;}
								path__pkgZbasolatoZcoreZbase69nv_u64 = T82_;
								nimln_(17);								T83_ = NIM_NIL;
								T83_ = newFileStream__pureZstreams_u1210(path__pkgZbasolatoZcoreZbase69nv_u64, ((tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA)0), ((NI)-1));
								if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZstreams_u1093(T83_); goto LA81_;}
								f__pkgZbasolatoZcoreZbase69nv_u65 = T83_;
								nimln_(18);								T84_[0] = TM__IUoffNuVge7huBUi8pG6JA_13;
								T84_[1] = path__pkgZbasolatoZcoreZbase69nv_u64;
								T84_[2] = TM__IUoffNuVge7huBUi8pG6JA_15;
								echoBinSafe(T84_, 3);
								nimln_(19);								nimZeroMem((void*)(&p__pkgZbasolatoZcoreZbase69nv_u66), sizeof(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg));
								p__pkgZbasolatoZcoreZbase69nv_u66.Sup.Sup.m_type = (&NTIv2__xKGlcBiu2pA13Poy9c49b9ayg_);
								nimln_(20);								npcopen((&p__pkgZbasolatoZcoreZbase69nv_u66), (*((tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg**) (&(f__pkgZbasolatoZcoreZbase69nv_u65)))), path__pkgZbasolatoZcoreZbase69nv_u64, ((NI)0));
								if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
								{
									nimln_(21);									while (1) {
										nimZeroMem((void*)(&e__pkgZbasolatoZcoreZbase69nv_u67), sizeof(tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ));
										e__pkgZbasolatoZcoreZbase69nv_u67.Sup.m_type = (&NTIv2__xinZeGTaQCxxN1TGrWYliQ_);
										nimln_(22);										npcnext((&p__pkgZbasolatoZcoreZbase69nv_u66), (&e__pkgZbasolatoZcoreZbase69nv_u67));
										if (NIM_UNLIKELY(*nimErr_)) goto LA87_;
										nimln_(23);										switch (e__pkgZbasolatoZcoreZbase69nv_u67.kind) {
										case ((tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw)0):
										{
											nimlf_(453, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");											eqdestroy___pureZparsecfg_u463((&e__pkgZbasolatoZcoreZbase69nv_u67));
											nimlf_(24, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.15.0-6ef054fa959d4a10421723c5ccbd3ea9b751c240/basolato/core/baseEnv.nim");											goto LA85;
										}
										break;
										case ((tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw)2):
										{
											nimln_(25);											if (!(((12 &((NU8)1<<((NU)((e__pkgZbasolatoZcoreZbase69nv_u67.kind))&7U)))!=0))) 											{ raiseFieldErrorStr(TM__IUoffNuVge7huBUi8pG6JA_17, dollar___pureZparsecfg_u22(e__pkgZbasolatoZcoreZbase69nv_u67.kind)); goto LA87_;
											}
											if (!(((12 &((NU8)1<<((NU)((e__pkgZbasolatoZcoreZbase69nv_u67.kind))&7U)))!=0))) 											{ raiseFieldErrorStr(TM__IUoffNuVge7huBUi8pG6JA_19, dollar___pureZparsecfg_u22(e__pkgZbasolatoZcoreZbase69nv_u67.kind)); goto LA87_;
											}
											putEnv__stdZenvvars_u23(e__pkgZbasolatoZcoreZbase69nv_u67._kind_3.key, e__pkgZbasolatoZcoreZbase69nv_u67._kind_3.value);
											if (NIM_UNLIKELY(*nimErr_)) goto LA87_;
										}
										break;
										default:
										{
										}
										break;
										}
										{
											LA87_:;
										}
										{
											nimlf_(453, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");											eqdestroy___pureZparsecfg_u463((&e__pkgZbasolatoZcoreZbase69nv_u67));
										}
										if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
									}
								} LA85: ;
								nimln_(230);								eqdestroy___pureZparsecfg_u62((&p__pkgZbasolatoZcoreZbase69nv_u66));
								nimlf_(1336, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");								eqdestroy___pureZstreams_u1093(f__pkgZbasolatoZcoreZbase69nv_u65);
								nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");								if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
								if (path__pkgZbasolatoZcoreZbase69nv_u64.p && !(path__pkgZbasolatoZcoreZbase69nv_u64.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path__pkgZbasolatoZcoreZbase69nv_u64.p);
}
								if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
								nimln_(2219);								eqdestroy___system_u5635(colontmpD__8);
								nimln_(394);								if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
								if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
								nimlf_(227, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");								T93_ = (int)0;
								T93_ = closedir(d_1);
								(void)(T93_);
								nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");								if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
								nimln_(934);								eqdestroy___stdZprivateZosdirs_u268((&f__pkgZbasolatoZcoreZbase69nv_u12));
								nimlf_(27, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.15.0-6ef054fa959d4a10421723c5ccbd3ea9b751c240/basolato/core/baseEnv.nim");								goto LA2;
								{
									LA81_:;
								}
								{
									nimlf_(230, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");									eqdestroy___pureZparsecfg_u62((&p__pkgZbasolatoZcoreZbase69nv_u66));
									nimlf_(1336, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");									eqdestroy___pureZstreams_u1093(f__pkgZbasolatoZcoreZbase69nv_u65);
									nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");									if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
									if (path__pkgZbasolatoZcoreZbase69nv_u64.p && !(path__pkgZbasolatoZcoreZbase69nv_u64.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path__pkgZbasolatoZcoreZbase69nv_u64.p);
}
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
							}
LA79_: ;
							{
								LA29_:;
							}
							{
								if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
								nimln_(2219);								eqdestroy___system_u5635(colontmpD__8);
								nimln_(394);								if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA18_;
						}
LA27_: ;
						{
							LA18_:;
						}
						{
							if (y_1.p && !(y_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(y_1.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
					} LA17: ;
				}
			} LA15: ;
			{
				LA14_:;
			}
			{
				int T102_;
				nimlf_(227, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osdirs.nim");				T102_ = (int)0;
				T102_ = closedir(d_1);
				(void)(T102_);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		}
LA4_: ;
		{
			LA3_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
			nimln_(934);			eqdestroy___stdZprivateZosdirs_u268((&f__pkgZbasolatoZcoreZbase69nv_u12));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	} LA2: ;
	nimlf_(31, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.15.0-6ef054fa959d4a10421723c5ccbd3ea9b751c240/basolato/core/baseEnv.nim");	T105_.len = 0; T105_.p = NIM_NIL;
	T105_ = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_21, TM__IUoffNuVge7huBUi8pG6JA_23);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T105_); goto LA1_;}
	SECRET_KEY__pkgZbasolatoZcoreZbase69nv_u25 = T105_;
	nimln_(33);	colontmpD_ = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_25, TM__IUoffNuVge7huBUi8pG6JA_27);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T106_ = (NIM_BOOL)0;
	T106_ = parseBool__pureZstrutils_u1113(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	IS_DISPLAY__pkgZbasolatoZcoreZbase69nv_u26 = T106_;
	nimln_(34);	colontmpD__2 = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_29, TM__IUoffNuVge7huBUi8pG6JA_30);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T107_ = (NIM_BOOL)0;
	T107_ = parseBool__pureZstrutils_u1113(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	IS_FILE__pkgZbasolatoZcoreZbase69nv_u27 = T107_;
	nimln_(35);	colontmpD__3 = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_32, TM__IUoffNuVge7huBUi8pG6JA_33);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T108_ = (NIM_BOOL)0;
	T108_ = parseBool__pureZstrutils_u1113(colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	IS_ERROR_FILE__pkgZbasolatoZcoreZbase69nv_u28 = T108_;
	nimln_(36);	colontmpD__4 = nosgetCurrentDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__5 = slash___stdZprivateZospaths2_u88(colontmpD__4, TM__IUoffNuVge7huBUi8pG6JA_37);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T109_.len = 0; T109_.p = NIM_NIL;
	T109_ = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_35, colontmpD__5);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T109_); goto LA1_;}
	LOG_DIR__pkgZbasolatoZcoreZbase69nv_u29 = T109_;
	nimln_(38);	colontmpD__6 = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_39, TM__IUoffNuVge7huBUi8pG6JA_41);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T110_ = (NI)0;
	T110_ = nsuParseInt(colontmpD__6);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	SESSION_TIME__pkgZbasolatoZcoreZbase69nv_u30 = T110_;
	nimln_(39);	T111_.len = 0; T111_.p = NIM_NIL;
	T111_ = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_43, TM__IUoffNuVge7huBUi8pG6JA_44);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T111_); goto LA1_;}
	COOKIE_DOMAINS__pkgZbasolatoZcoreZbase69nv_u31 = T111_;
	nimln_(40);	colontmpD__7 = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_46, TM__IUoffNuVge7huBUi8pG6JA_47);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T112_ = (NIM_BOOL)0;
	T112_ = parseBool__pureZstrutils_u1113(colontmpD__7);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	ENABLE_ANONYMOUS_COOKIE__pkgZbasolatoZcoreZbase69nv_u32 = T112_;
	nimln_(43);	T113_.len = 0; T113_.p = NIM_NIL;
	T113_ = getEnv__stdZenvvars_u15(TM__IUoffNuVge7huBUi8pG6JA_49, TM__IUoffNuVge7huBUi8pG6JA_51);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T113_); goto LA1_;}
	LOCALE__pkgZbasolatoZcoreZbase69nv_u33 = T113_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

