/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pbasolato@score@ssecurity@ssession_db.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pbasolato@score@ssecurity@ssession_db.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyTuple__qxD9bC9cUNUzMyLUTWovEpGw tyTuple__qxD9bC9cUNUzMyLUTWovEpGw;
typedef struct tyObject_FuturecolonObjectType___SW3LgPpEa8pGsY9bL64kB9cQ tyObject_FuturecolonObjectType___SW3LgPpEa8pGsY9bL64kB9cQ;
typedef struct tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_JsonNodeObj__9cNypU6qSyKQq2YqeEuiAyA tyObject_JsonNodeObj__9cNypU6qSyKQq2YqeEuiAyA;
typedef struct tyObject_FuturecolonObjectType___jslbu2t1zrAO9cyh2aNrEHQ tyObject_FuturecolonObjectType___jslbu2t1zrAO9cyh2aNrEHQ;
typedef struct tyObject_FuturecolonObjectType___A48CNmn9cC0ZX5NgpJa9bfzg tyObject_FuturecolonObjectType___A48CNmn9cC0ZX5NgpJa9bfzg;
typedef struct tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg;
typedef struct tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA;
typedef struct tyTuple__TGoPjOunaLBwuXSEEclIhw tyTuple__TGoPjOunaLBwuXSEEclIhw;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___SW3LgPpEa8pGsY9bL64kB9cQ*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__lxlV5qPzMvEKLX1DjWXnSA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ClP_0) (NimStringV2 key_p0, NimStringV2 value_p1, void* ClE_0);
void* ClE_0;
} tyProc__TGYqRQEV9afBBZ9cgrAw9ah1A;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ClP_0) (NimStringV2 key_p0, tyObject_JsonNodeObj__9cNypU6qSyKQq2YqeEuiAyA* value_p1, void* ClE_0);
void* ClE_0;
} tyProc__ybBX9aNtMG9aiX8C9c9crteeSQ;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___jslbu2t1zrAO9cyh2aNrEHQ*, ClP_0) (NimStringV2 key_p0, void* ClE_0);
void* ClE_0;
} tyProc__7VqxoLhP05V18MPsvxvzZw;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___SW3LgPpEa8pGsY9bL64kB9cQ*, ClP_0) (NimStringV2 key_p0, void* ClE_0);
void* ClE_0;
} tyProc__d1EW2j9cKYZkRJ9bIVhyqTKQ;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___A48CNmn9cC0ZX5NgpJa9bfzg*, ClP_0) (NimStringV2 key_p0, void* ClE_0);
void* ClE_0;
} tyProc__0tNWDCurADj8oCqAQJaEWw;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___A48CNmn9cC0ZX5NgpJa9bfzg*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__0Tv6yehJYe9cIkhQjz5h6Ig;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ClP_0) (NimStringV2 key_p0, void* ClE_0);
void* ClE_0;
} tyProc__jQwn9akaXS6JC9bNVRduw5fQ;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__9cTHZf9cmY4bzdf4QvFANU4w;
struct tyTuple__qxD9bC9cUNUzMyLUTWovEpGw {
	tyProc__lxlV5qPzMvEKLX1DjWXnSA Field0;
	tyProc__TGYqRQEV9afBBZ9cgrAw9ah1A Field1;
	tyProc__ybBX9aNtMG9aiX8C9c9crteeSQ Field2;
	tyProc__7VqxoLhP05V18MPsvxvzZw Field3;
	tyProc__d1EW2j9cKYZkRJ9bIVhyqTKQ Field4;
	tyProc__0tNWDCurADj8oCqAQJaEWw Field5;
	tyProc__0Tv6yehJYe9cIkhQjz5h6Ig Field6;
	tyProc__jQwn9akaXS6JC9bNVRduw5fQ Field7;
	tyProc__9cTHZf9cmY4bzdf4QvFANU4w Field8;
	tyProc__9cTHZf9cmY4bzdf4QvFANU4w Field9;
};
struct tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ {
	tyTuple__qxD9bC9cUNUzMyLUTWovEpGw impl;
};
struct tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA {
	NI len;
	NI cap;
	tyTuple__TGoPjOunaLBwuXSEEclIhw* d;
};
struct tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg {
	tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw traceStack;
	tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZbasolatoZcoreZsecurityZsession95db_u1596)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZbasolatoZcoreZsecurityZsession95db_u243)(tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3520)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZbasolatoZcoreZsecurityZsession95db_u255)(tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3041)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3049)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__srP8R9aQ0pO9aruttXO1eqgQ_;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static NIM_CONST NU32 TM__utYx9cg4nrclL79bdtVQWXwQ_2[1] = {3019654912};
N_LIB_PRIVATE TNimTypeV2 NTIv2__srP8R9aQ0pO9aruttXO1eqgQ_ = {.destructor = (void*)rttiDestroy__pkgZbasolatoZcoreZsecurityZsession95db_u1596, .size = sizeof(tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ), .align = (NI16) NIM_ALIGNOF(tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ), .depth = 0, .display = TM__utYx9cg4nrclL79bdtVQWXwQ_2, .traceImpl = (void*)eqtrace___pkgZbasolatoZcoreZsecurityZsession95db_u255, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(518, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimlf_(521, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3520(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZbasolatoZcoreZsecurityZsession95db_u243)(tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field0.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).impl.Field0.ClE_0);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field1.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).impl.Field1.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field2.ClE_0);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).impl.Field2.ClE_0);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field3.ClE_0);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).impl.Field3.ClE_0);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field4.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).impl.Field4.ClE_0);
	}
LA24_: ;
	{
		NIM_BOOL T28_;
		T28_ = (NIM_BOOL)0;
		T28_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field5.ClE_0);
		if (!T28_) goto LA29_;
		nimDestroyAndDispose((*dest_p0).impl.Field5.ClE_0);
	}
LA29_: ;
	{
		NIM_BOOL T33_;
		T33_ = (NIM_BOOL)0;
		T33_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field6.ClE_0);
		if (!T33_) goto LA34_;
		nimDestroyAndDispose((*dest_p0).impl.Field6.ClE_0);
	}
LA34_: ;
	{
		NIM_BOOL T38_;
		T38_ = (NIM_BOOL)0;
		T38_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field7.ClE_0);
		if (!T38_) goto LA39_;
		nimDestroyAndDispose((*dest_p0).impl.Field7.ClE_0);
	}
LA39_: ;
	{
		NIM_BOOL T43_;
		T43_ = (NIM_BOOL)0;
		T43_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field8.ClE_0);
		if (!T43_) goto LA44_;
		nimDestroyAndDispose((*dest_p0).impl.Field8.ClE_0);
	}
LA44_: ;
	{
		NIM_BOOL T48_;
		T48_ = (NIM_BOOL)0;
		T48_ = nimDecRefIsLastCyclicDyn((*dest_p0).impl.Field9.ClE_0);
		if (!T48_) goto LA49_;
		nimDestroyAndDispose((*dest_p0).impl.Field9.ClE_0);
	}
LA49_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZbasolatoZcoreZsecurityZsession95db_u1596)(void* dest_p0) {
	eqdestroy___pkgZbasolatoZcoreZsecurityZsession95db_u243(((tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ*) (dest_p0)));
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(360, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3041)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3049(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(138, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg*) (env_p1));
		nimln_(141);		add__system_u3041((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZbasolatoZcoreZsecurityZsession95db_u255)(tyObject_SessionDbcolonObjectType___srP8R9aQ0pO9aruttXO1eqgQ* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).impl.Field0.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field1.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field2.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field3.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field4.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field5.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field6.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field7.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field8.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).impl.Field9.ClE_0), env_p1);
}
