/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@phttpcore.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@phttpcore.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyObject_Table__7VMwcdKPjTOBWJKprTjBww tyObject_Table__7VMwcdKPjTOBWJKprTjBww;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA;
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
struct tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ {
	tyObject_Table__7VMwcdKPjTOBWJKprTjBww* table;
	NIM_BOOL isTitleCase;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u302)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZhttpcore_u1255)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* t_p0, NimStringV2 key_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val_p2);
static N_INLINE(NimStringV2, toCaseInsensitive__pureZhttpcore_u110)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toTitleCase__pureZhttpcore_u101)(NimStringV2 s_p0);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2474)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__7VMwcdKPjTOBWJKprTjBww*, newTable__pureZhttpcore_u133)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZhttpcore_u585)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D___pureZhttpcore_u960)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, eqdup___system_u5641)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZhttpcore_u541)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Evu9b2R1utZubyCikahWx1g_2 = { 4 | NIM_STRLIT_FLAG, "HEAD" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_3 = {4, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_2};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Evu9b2R1utZubyCikahWx1g_4 = { 3 | NIM_STRLIT_FLAG, "GET" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_5 = {3, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Evu9b2R1utZubyCikahWx1g_6 = { 4 | NIM_STRLIT_FLAG, "POST" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_7 = {4, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_6};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Evu9b2R1utZubyCikahWx1g_8 = { 3 | NIM_STRLIT_FLAG, "PUT" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_9 = {3, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_8};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Evu9b2R1utZubyCikahWx1g_10 = { 6 | NIM_STRLIT_FLAG, "DELETE" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_11 = {6, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_10};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Evu9b2R1utZubyCikahWx1g_12 = { 5 | NIM_STRLIT_FLAG, "TRACE" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_13 = {5, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_12};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Evu9b2R1utZubyCikahWx1g_14 = { 7 | NIM_STRLIT_FLAG, "OPTIONS" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_15 = {7, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_14};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Evu9b2R1utZubyCikahWx1g_16 = { 7 | NIM_STRLIT_FLAG, "CONNECT" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_17 = {7, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_16};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Evu9b2R1utZubyCikahWx1g_18 = { 5 | NIM_STRLIT_FLAG, "PATCH" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_19 = {5, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_18};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Evu9b2R1utZubyCikahWx1g_20 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_21 = {0, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_20};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__Evu9b2R1utZubyCikahWx1g_24 = { 12 | NIM_STRLIT_FLAG, "100 Continue" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_25 = {12, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_24};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Evu9b2R1utZubyCikahWx1g_26 = { 23 | NIM_STRLIT_FLAG, "101 Switching Protocols" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_27 = {23, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_26};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__Evu9b2R1utZubyCikahWx1g_28 = { 14 | NIM_STRLIT_FLAG, "102 Processing" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_29 = {14, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_28};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__Evu9b2R1utZubyCikahWx1g_30 = { 15 | NIM_STRLIT_FLAG, "103 Early Hints" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_31 = {15, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_30};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Evu9b2R1utZubyCikahWx1g_32 = { 6 | NIM_STRLIT_FLAG, "200 OK" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_33 = {6, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_32};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__Evu9b2R1utZubyCikahWx1g_34 = { 11 | NIM_STRLIT_FLAG, "201 Created" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_35 = {11, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_34};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__Evu9b2R1utZubyCikahWx1g_36 = { 12 | NIM_STRLIT_FLAG, "202 Accepted" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_37 = {12, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_36};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__Evu9b2R1utZubyCikahWx1g_38 = { 33 | NIM_STRLIT_FLAG, "203 Non-Authoritative Information" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_39 = {33, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_38};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__Evu9b2R1utZubyCikahWx1g_40 = { 14 | NIM_STRLIT_FLAG, "204 No Content" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_41 = {14, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_40};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__Evu9b2R1utZubyCikahWx1g_42 = { 17 | NIM_STRLIT_FLAG, "205 Reset Content" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_43 = {17, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_42};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Evu9b2R1utZubyCikahWx1g_44 = { 19 | NIM_STRLIT_FLAG, "206 Partial Content" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_45 = {19, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_44};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Evu9b2R1utZubyCikahWx1g_46 = { 16 | NIM_STRLIT_FLAG, "207 Multi-Status" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_47 = {16, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_46};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Evu9b2R1utZubyCikahWx1g_48 = { 20 | NIM_STRLIT_FLAG, "208 Already Reported" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_49 = {20, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_48};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__Evu9b2R1utZubyCikahWx1g_50 = { 11 | NIM_STRLIT_FLAG, "226 IM Used" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_51 = {11, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_50};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Evu9b2R1utZubyCikahWx1g_52 = { 20 | NIM_STRLIT_FLAG, "300 Multiple Choices" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_53 = {20, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_52};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__Evu9b2R1utZubyCikahWx1g_54 = { 21 | NIM_STRLIT_FLAG, "301 Moved Permanently" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_55 = {21, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_54};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__Evu9b2R1utZubyCikahWx1g_56 = { 9 | NIM_STRLIT_FLAG, "302 Found" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_57 = {9, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_56};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Evu9b2R1utZubyCikahWx1g_58 = { 13 | NIM_STRLIT_FLAG, "303 See Other" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_59 = {13, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_58};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Evu9b2R1utZubyCikahWx1g_60 = { 16 | NIM_STRLIT_FLAG, "304 Not Modified" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_61 = {16, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_60};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Evu9b2R1utZubyCikahWx1g_62 = { 13 | NIM_STRLIT_FLAG, "305 Use Proxy" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_63 = {13, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_62};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Evu9b2R1utZubyCikahWx1g_64 = { 22 | NIM_STRLIT_FLAG, "307 Temporary Redirect" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_65 = {22, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_64};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Evu9b2R1utZubyCikahWx1g_66 = { 22 | NIM_STRLIT_FLAG, "308 Permanent Redirect" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_67 = {22, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_66};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__Evu9b2R1utZubyCikahWx1g_68 = { 15 | NIM_STRLIT_FLAG, "400 Bad Request" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_69 = {15, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_68};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Evu9b2R1utZubyCikahWx1g_70 = { 16 | NIM_STRLIT_FLAG, "401 Unauthorized" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_71 = {16, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_70};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Evu9b2R1utZubyCikahWx1g_72 = { 20 | NIM_STRLIT_FLAG, "402 Payment Required" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_73 = {20, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_72};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Evu9b2R1utZubyCikahWx1g_74 = { 13 | NIM_STRLIT_FLAG, "403 Forbidden" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_75 = {13, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_74};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Evu9b2R1utZubyCikahWx1g_76 = { 13 | NIM_STRLIT_FLAG, "404 Not Found" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_77 = {13, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_76};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Evu9b2R1utZubyCikahWx1g_78 = { 22 | NIM_STRLIT_FLAG, "405 Method Not Allowed" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_79 = {22, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_78};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__Evu9b2R1utZubyCikahWx1g_80 = { 18 | NIM_STRLIT_FLAG, "406 Not Acceptable" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_81 = {18, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_80};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__Evu9b2R1utZubyCikahWx1g_82 = { 33 | NIM_STRLIT_FLAG, "407 Proxy Authentication Required" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_83 = {33, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_82};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Evu9b2R1utZubyCikahWx1g_84 = { 19 | NIM_STRLIT_FLAG, "408 Request Timeout" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_85 = {19, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_84};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__Evu9b2R1utZubyCikahWx1g_86 = { 12 | NIM_STRLIT_FLAG, "409 Conflict" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_87 = {12, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_86};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__Evu9b2R1utZubyCikahWx1g_88 = { 8 | NIM_STRLIT_FLAG, "410 Gone" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_89 = {8, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_88};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Evu9b2R1utZubyCikahWx1g_90 = { 19 | NIM_STRLIT_FLAG, "411 Length Required" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_91 = {19, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_90};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Evu9b2R1utZubyCikahWx1g_92 = { 23 | NIM_STRLIT_FLAG, "412 Precondition Failed" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_93 = {23, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_92};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__Evu9b2R1utZubyCikahWx1g_94 = { 28 | NIM_STRLIT_FLAG, "413 Request Entity Too Large" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_95 = {28, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_94};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__Evu9b2R1utZubyCikahWx1g_96 = { 24 | NIM_STRLIT_FLAG, "414 Request-URI Too Long" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_97 = {24, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_96};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__Evu9b2R1utZubyCikahWx1g_98 = { 26 | NIM_STRLIT_FLAG, "415 Unsupported Media Type" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_99 = {26, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_98};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__Evu9b2R1utZubyCikahWx1g_100 = { 35 | NIM_STRLIT_FLAG, "416 Requested Range Not Satisfiable" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_101 = {35, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_100};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Evu9b2R1utZubyCikahWx1g_102 = { 22 | NIM_STRLIT_FLAG, "417 Expectation Failed" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_103 = {22, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_102};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Evu9b2R1utZubyCikahWx1g_104 = { 16 | NIM_STRLIT_FLAG, "418 I\'m a teapot" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_105 = {16, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_104};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Evu9b2R1utZubyCikahWx1g_106 = { 23 | NIM_STRLIT_FLAG, "421 Misdirected Request" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_107 = {23, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_106};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__Evu9b2R1utZubyCikahWx1g_108 = { 24 | NIM_STRLIT_FLAG, "422 Unprocessable Entity" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_109 = {24, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_108};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__Evu9b2R1utZubyCikahWx1g_110 = { 10 | NIM_STRLIT_FLAG, "423 Locked" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_111 = {10, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_110};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__Evu9b2R1utZubyCikahWx1g_112 = { 21 | NIM_STRLIT_FLAG, "424 Failed Dependency" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_113 = {21, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_112};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Evu9b2R1utZubyCikahWx1g_114 = { 13 | NIM_STRLIT_FLAG, "425 Too Early" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_115 = {13, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_114};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Evu9b2R1utZubyCikahWx1g_116 = { 20 | NIM_STRLIT_FLAG, "426 Upgrade Required" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_117 = {20, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_116};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__Evu9b2R1utZubyCikahWx1g_118 = { 25 | NIM_STRLIT_FLAG, "428 Precondition Required" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_119 = {25, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_118};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__Evu9b2R1utZubyCikahWx1g_120 = { 21 | NIM_STRLIT_FLAG, "429 Too Many Requests" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_121 = {21, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_120};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__Evu9b2R1utZubyCikahWx1g_122 = { 35 | NIM_STRLIT_FLAG, "431 Request Header Fields Too Large" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_123 = {35, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_122};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__Evu9b2R1utZubyCikahWx1g_124 = { 33 | NIM_STRLIT_FLAG, "451 Unavailable For Legal Reasons" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_125 = {33, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_124};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__Evu9b2R1utZubyCikahWx1g_126 = { 25 | NIM_STRLIT_FLAG, "500 Internal Server Error" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_127 = {25, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_126};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Evu9b2R1utZubyCikahWx1g_128 = { 19 | NIM_STRLIT_FLAG, "501 Not Implemented" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_129 = {19, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_128};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__Evu9b2R1utZubyCikahWx1g_130 = { 15 | NIM_STRLIT_FLAG, "502 Bad Gateway" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_131 = {15, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_130};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Evu9b2R1utZubyCikahWx1g_132 = { 23 | NIM_STRLIT_FLAG, "503 Service Unavailable" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_133 = {23, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_132};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Evu9b2R1utZubyCikahWx1g_134 = { 19 | NIM_STRLIT_FLAG, "504 Gateway Timeout" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_135 = {19, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_134};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__Evu9b2R1utZubyCikahWx1g_136 = { 30 | NIM_STRLIT_FLAG, "505 HTTP Version Not Supported" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_137 = {30, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_136};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__Evu9b2R1utZubyCikahWx1g_138 = { 27 | NIM_STRLIT_FLAG, "506 Variant Also Negotiates" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_139 = {27, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_138};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__Evu9b2R1utZubyCikahWx1g_140 = { 24 | NIM_STRLIT_FLAG, "507 Insufficient Storage" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_141 = {24, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_140};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__Evu9b2R1utZubyCikahWx1g_142 = { 17 | NIM_STRLIT_FLAG, "508 Loop Detected" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_143 = {17, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_142};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Evu9b2R1utZubyCikahWx1g_144 = { 16 | NIM_STRLIT_FLAG, "510 Not Extended" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_145 = {16, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_144};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__Evu9b2R1utZubyCikahWx1g_146 = { 35 | NIM_STRLIT_FLAG, "511 Network Authentication Required" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_147 = {35, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_146};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZhttpcore_u34)(tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)0):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_3;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)1):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_5;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)2):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_7;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)3):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_9;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)4):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_11;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)5):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_13;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)6):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_15;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)7):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_17;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)8):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_19;
	}
	break;
	default:
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_21;
	}
	break;
	}
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(220);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(221);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimln_(235);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4) & (64 - 1))) == ((NI)0))) goto LA8_;
			nimln_(236);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).table);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u302((*dest_p0).table);
		nimRawDispose((*dest_p0).table, ((NI)8));
	}
LA4_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(360, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(88, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	(*((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T2_))).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZhttpcore_u443)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ** dest_p0, tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pureZhttpcore_u414((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2474(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toTitleCase__pureZhttpcore_u101)(NimStringV2 s_p0) {
	NimStringV2 result;
	NIM_BOOL upper_1;
NIM_BOOL* nimErr_;
	nimfr_("toTitleCase", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(123, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	nimln_(124);	upper_1 = NIM_TRUE;
	{
		NI i_1;
		NI colontmp_;
		NI TM__Evu9b2R1utZubyCikahWx1g_22;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(125, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__Evu9b2R1utZubyCikahWx1g_22)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__Evu9b2R1utZubyCikahWx1g_22);
		nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR colontmpD_;
				NIM_CHAR colontmpD__2;
				NI TM__Evu9b2R1utZubyCikahWx1g_23;
				if (!(res_1 <= colontmp_)) goto LA3;
				colontmpD_ = (NIM_CHAR)0;
				colontmpD__2 = (NIM_CHAR)0;
				nimlf_(125, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");				i_1 = ((NI) (res_1));
				nimln_(126);				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				{
					if (!upper_1) goto LA6_;
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					colontmpD_ = nsuToUpperAsciiChar(s_p0.p->data[i_1]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					result.p->data[i_1] = colontmpD_;
				}
				goto LA4_;
LA6_: ;
				{
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					colontmpD__2 = nsuToLowerAsciiChar(s_p0.p->data[i_1]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					result.p->data[i_1] = colontmpD__2;
				}
LA4_: ;
				nimln_(127);				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				upper_1 = ((NU8)(s_p0.p->data[i_1]) == (NU8)(45));
				nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__Evu9b2R1utZubyCikahWx1g_23)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__Evu9b2R1utZubyCikahWx1g_23);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, toCaseInsensitive__pureZhttpcore_u110)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 s_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("toCaseInsensitive", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(131, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(*headers_p0).isTitleCase) goto LA4_;
		nimln_(129);		nimln_(131);		result = toTitleCase__pureZhttpcore_u101(s_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA4_: ;
	{
		nimln_(129);		nimln_(131);		result = nsuToLowerAsciiStr(s_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA2_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZhttpcore_u3200)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 key_p1, NimStringV2 value_p2) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("[]=", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(183);	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_.len = 1; T1_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD__2 = eqdup___system_u2728(value_p2);
	T1_.p->data[0] = colontmpD__2;
	nimlf_(183, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	X5BX5Deq___pureZhttpcore_u1255((*headers_p0).table, colontmpD_, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*, eqdup___pureZhttpcore_u446)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* src_p0) {
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u440)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*, newHttpHeaders__pureZhttpcore_u114)(NIM_BOOL titleCase_p0) {
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* result;
	NIM_BOOL colontmpD_;
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newHttpHeaders", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = (NIM_BOOL)0;
	nimlf_(136, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*) nimNewObjUninit(sizeof(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ), NIM_ALIGNOF(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ));
	(*T1_).table = newTable__pureZhttpcore_u133(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD_ = titleCase_p0;
	(*T1_).isTitleCase = colontmpD_;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZhttpcore_u4008)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("hasKey", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(220);	nimln_(219);	nimln_(220);	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = hasKey__pureZhttpcore_u585((*headers_p0).table, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toString__pureZhttpcore_u3138)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ values_p0) {
	NimStringV2 result;
	nimfr_("toString", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(171, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (((NI)0) < 0 || ((NI)0) >= values_p0.len){ raiseIndexError2(((NI)0),values_p0.len-1); goto BeforeRet_;
	}
	eqcopy___system_u2725((&result), values_p0.p->data[((NI)0)]);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, X5BX5D___pureZhttpcore_u3021)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 key_p1) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ tmp_1;
	NimStringV2 colontmpD_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__2;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* T2_;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	tmp_1.len = 0; tmp_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimlf_(167, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T2_ = X5BX5D___pureZhttpcore_u960((*headers_p0).table, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	tmp_1 = (*T2_);
	nimln_(168);	nimln_(158);	nimln_(168);	nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD__2 = eqdup___system_u5641(tmp_1);
	result = colontmpD__2;
	nimln_(394);	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u3102)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].p && !(dest_p0.p->data[colontmp_].p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NimStringV2));
}
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*, newHttpHeaders__pureZhttpcore_u462)(tyTuple__UV3llMMYFckfui8YMBuUZA* keyValuePairs_p0, NI keyValuePairs_p0Len_0, NIM_BOOL titleCase_p1) {
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* result;
	NIM_BOOL colontmpD_;
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newHttpHeaders", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = (NIM_BOOL)0;
	nimlf_(142, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*) nimNewObjUninit(sizeof(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ), NIM_ALIGNOF(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ));
	(*T1_).table = newTable__pureZhttpcore_u133(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD_ = titleCase_p1;
	(*T1_).isTitleCase = colontmpD_;
	result = T1_;
	{
		tyTuple__UV3llMMYFckfui8YMBuUZA* pair_1;
		NI i_1;
		pair_1 = (tyTuple__UV3llMMYFckfui8YMBuUZA*)0;
		nimlf_(18, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(19);			while (1) {
				NimStringV2 key_1;
				if (!(i_1 < keyValuePairs_p0Len_0)) goto LA4;
				key_1.len = 0; key_1.p = NIM_NIL;
				nimlf_(144, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");				if (i_1 < 0 || i_1 >= keyValuePairs_p0Len_0){ raiseIndexError2(i_1,keyValuePairs_p0Len_0-1); goto LA5_;
				}
				pair_1 = (&keyValuePairs_p0[i_1]);
				nimln_(145);				key_1 = toCaseInsensitive__pureZhttpcore_u110(result, (*pair_1).Field0);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				nimln_(147);				{
					NIM_BOOL T8_;
					NimStringV2 colontmpD__2;
					tySequence__sM4lkSb7zS6F7OVMvW9cffQ* T11_;
					T8_ = (NIM_BOOL)0;
					T8_ = contains__pureZhttpcore_u541((*result).table, key_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					if (!T8_) goto LA9_;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					nimln_(148);					T11_ = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
					T11_ = X5BX5D___pureZhttpcore_u960((*result).table, key_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					colontmpD__2 = eqdup___system_u2728((*pair_1).Field1);
					nimlf_(148, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");					add__stdZenumutils_u70((&(*T11_)), colontmpD__2);
				}
				goto LA6_;
LA9_: ;
				{
					NimStringV2 colontmpD__3;
					tySequence__sM4lkSb7zS6F7OVMvW9cffQ T13_;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					nimln_(150);					T13_.len = 0; T13_.p = NIM_NIL;
					T13_.len = 1; T13_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					colontmpD__3 = eqdup___system_u2728((*pair_1).Field1);
					T13_.p->data[0] = colontmpD__3;
					nimlf_(150, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");					X5BX5Deq___pureZhttpcore_u1255((*result).table, key_1, T13_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				}
LA6_: ;
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				{
					LA5_:;
				}
				{
					nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZhttpcore_u4267)(NI code_p0) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(282, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	switch (code_p0) {
	case ((NI)100):
	{
		nimln_(278);		nimln_(283);		result = TM__Evu9b2R1utZubyCikahWx1g_25;
	}
	break;
	case ((NI)101):
	{
		nimln_(278);		nimln_(284);		result = TM__Evu9b2R1utZubyCikahWx1g_27;
	}
	break;
	case ((NI)102):
	{
		nimln_(278);		nimln_(285);		result = TM__Evu9b2R1utZubyCikahWx1g_29;
	}
	break;
	case ((NI)103):
	{
		nimln_(278);		nimln_(286);		result = TM__Evu9b2R1utZubyCikahWx1g_31;
	}
	break;
	case ((NI)200):
	{
		nimln_(278);		nimln_(287);		result = TM__Evu9b2R1utZubyCikahWx1g_33;
	}
	break;
	case ((NI)201):
	{
		nimln_(278);		nimln_(288);		result = TM__Evu9b2R1utZubyCikahWx1g_35;
	}
	break;
	case ((NI)202):
	{
		nimln_(278);		nimln_(289);		result = TM__Evu9b2R1utZubyCikahWx1g_37;
	}
	break;
	case ((NI)203):
	{
		nimln_(278);		nimln_(290);		result = TM__Evu9b2R1utZubyCikahWx1g_39;
	}
	break;
	case ((NI)204):
	{
		nimln_(278);		nimln_(291);		result = TM__Evu9b2R1utZubyCikahWx1g_41;
	}
	break;
	case ((NI)205):
	{
		nimln_(278);		nimln_(292);		result = TM__Evu9b2R1utZubyCikahWx1g_43;
	}
	break;
	case ((NI)206):
	{
		nimln_(278);		nimln_(293);		result = TM__Evu9b2R1utZubyCikahWx1g_45;
	}
	break;
	case ((NI)207):
	{
		nimln_(278);		nimln_(294);		result = TM__Evu9b2R1utZubyCikahWx1g_47;
	}
	break;
	case ((NI)208):
	{
		nimln_(278);		nimln_(295);		result = TM__Evu9b2R1utZubyCikahWx1g_49;
	}
	break;
	case ((NI)226):
	{
		nimln_(278);		nimln_(296);		result = TM__Evu9b2R1utZubyCikahWx1g_51;
	}
	break;
	case ((NI)300):
	{
		nimln_(278);		nimln_(297);		result = TM__Evu9b2R1utZubyCikahWx1g_53;
	}
	break;
	case ((NI)301):
	{
		nimln_(278);		nimln_(298);		result = TM__Evu9b2R1utZubyCikahWx1g_55;
	}
	break;
	case ((NI)302):
	{
		nimln_(278);		nimln_(299);		result = TM__Evu9b2R1utZubyCikahWx1g_57;
	}
	break;
	case ((NI)303):
	{
		nimln_(278);		nimln_(300);		result = TM__Evu9b2R1utZubyCikahWx1g_59;
	}
	break;
	case ((NI)304):
	{
		nimln_(278);		nimln_(301);		result = TM__Evu9b2R1utZubyCikahWx1g_61;
	}
	break;
	case ((NI)305):
	{
		nimln_(278);		nimln_(302);		result = TM__Evu9b2R1utZubyCikahWx1g_63;
	}
	break;
	case ((NI)307):
	{
		nimln_(278);		nimln_(303);		result = TM__Evu9b2R1utZubyCikahWx1g_65;
	}
	break;
	case ((NI)308):
	{
		nimln_(278);		nimln_(304);		result = TM__Evu9b2R1utZubyCikahWx1g_67;
	}
	break;
	case ((NI)400):
	{
		nimln_(278);		nimln_(305);		result = TM__Evu9b2R1utZubyCikahWx1g_69;
	}
	break;
	case ((NI)401):
	{
		nimln_(278);		nimln_(306);		result = TM__Evu9b2R1utZubyCikahWx1g_71;
	}
	break;
	case ((NI)402):
	{
		nimln_(278);		nimln_(307);		result = TM__Evu9b2R1utZubyCikahWx1g_73;
	}
	break;
	case ((NI)403):
	{
		nimln_(278);		nimln_(308);		result = TM__Evu9b2R1utZubyCikahWx1g_75;
	}
	break;
	case ((NI)404):
	{
		nimln_(278);		nimln_(309);		result = TM__Evu9b2R1utZubyCikahWx1g_77;
	}
	break;
	case ((NI)405):
	{
		nimln_(278);		nimln_(310);		result = TM__Evu9b2R1utZubyCikahWx1g_79;
	}
	break;
	case ((NI)406):
	{
		nimln_(278);		nimln_(311);		result = TM__Evu9b2R1utZubyCikahWx1g_81;
	}
	break;
	case ((NI)407):
	{
		nimln_(278);		nimln_(312);		result = TM__Evu9b2R1utZubyCikahWx1g_83;
	}
	break;
	case ((NI)408):
	{
		nimln_(278);		nimln_(313);		result = TM__Evu9b2R1utZubyCikahWx1g_85;
	}
	break;
	case ((NI)409):
	{
		nimln_(278);		nimln_(314);		result = TM__Evu9b2R1utZubyCikahWx1g_87;
	}
	break;
	case ((NI)410):
	{
		nimln_(278);		nimln_(315);		result = TM__Evu9b2R1utZubyCikahWx1g_89;
	}
	break;
	case ((NI)411):
	{
		nimln_(278);		nimln_(316);		result = TM__Evu9b2R1utZubyCikahWx1g_91;
	}
	break;
	case ((NI)412):
	{
		nimln_(278);		nimln_(317);		result = TM__Evu9b2R1utZubyCikahWx1g_93;
	}
	break;
	case ((NI)413):
	{
		nimln_(278);		nimln_(318);		result = TM__Evu9b2R1utZubyCikahWx1g_95;
	}
	break;
	case ((NI)414):
	{
		nimln_(278);		nimln_(319);		result = TM__Evu9b2R1utZubyCikahWx1g_97;
	}
	break;
	case ((NI)415):
	{
		nimln_(278);		nimln_(320);		result = TM__Evu9b2R1utZubyCikahWx1g_99;
	}
	break;
	case ((NI)416):
	{
		nimln_(278);		nimln_(321);		result = TM__Evu9b2R1utZubyCikahWx1g_101;
	}
	break;
	case ((NI)417):
	{
		nimln_(278);		nimln_(322);		result = TM__Evu9b2R1utZubyCikahWx1g_103;
	}
	break;
	case ((NI)418):
	{
		nimln_(278);		nimln_(323);		result = TM__Evu9b2R1utZubyCikahWx1g_105;
	}
	break;
	case ((NI)421):
	{
		nimln_(278);		nimln_(324);		result = TM__Evu9b2R1utZubyCikahWx1g_107;
	}
	break;
	case ((NI)422):
	{
		nimln_(278);		nimln_(325);		result = TM__Evu9b2R1utZubyCikahWx1g_109;
	}
	break;
	case ((NI)423):
	{
		nimln_(278);		nimln_(326);		result = TM__Evu9b2R1utZubyCikahWx1g_111;
	}
	break;
	case ((NI)424):
	{
		nimln_(278);		nimln_(327);		result = TM__Evu9b2R1utZubyCikahWx1g_113;
	}
	break;
	case ((NI)425):
	{
		nimln_(278);		nimln_(328);		result = TM__Evu9b2R1utZubyCikahWx1g_115;
	}
	break;
	case ((NI)426):
	{
		nimln_(278);		nimln_(329);		result = TM__Evu9b2R1utZubyCikahWx1g_117;
	}
	break;
	case ((NI)428):
	{
		nimln_(278);		nimln_(330);		result = TM__Evu9b2R1utZubyCikahWx1g_119;
	}
	break;
	case ((NI)429):
	{
		nimln_(278);		nimln_(331);		result = TM__Evu9b2R1utZubyCikahWx1g_121;
	}
	break;
	case ((NI)431):
	{
		nimln_(278);		nimln_(332);		result = TM__Evu9b2R1utZubyCikahWx1g_123;
	}
	break;
	case ((NI)451):
	{
		nimln_(278);		nimln_(333);		result = TM__Evu9b2R1utZubyCikahWx1g_125;
	}
	break;
	case ((NI)500):
	{
		nimln_(278);		nimln_(334);		result = TM__Evu9b2R1utZubyCikahWx1g_127;
	}
	break;
	case ((NI)501):
	{
		nimln_(278);		nimln_(335);		result = TM__Evu9b2R1utZubyCikahWx1g_129;
	}
	break;
	case ((NI)502):
	{
		nimln_(278);		nimln_(336);		result = TM__Evu9b2R1utZubyCikahWx1g_131;
	}
	break;
	case ((NI)503):
	{
		nimln_(278);		nimln_(337);		result = TM__Evu9b2R1utZubyCikahWx1g_133;
	}
	break;
	case ((NI)504):
	{
		nimln_(278);		nimln_(338);		result = TM__Evu9b2R1utZubyCikahWx1g_135;
	}
	break;
	case ((NI)505):
	{
		nimln_(278);		nimln_(339);		result = TM__Evu9b2R1utZubyCikahWx1g_137;
	}
	break;
	case ((NI)506):
	{
		nimln_(278);		nimln_(340);		result = TM__Evu9b2R1utZubyCikahWx1g_139;
	}
	break;
	case ((NI)507):
	{
		nimln_(278);		nimln_(341);		result = TM__Evu9b2R1utZubyCikahWx1g_141;
	}
	break;
	case ((NI)508):
	{
		nimln_(278);		nimln_(342);		result = TM__Evu9b2R1utZubyCikahWx1g_143;
	}
	break;
	case ((NI)510):
	{
		nimln_(278);		nimln_(343);		result = TM__Evu9b2R1utZubyCikahWx1g_145;
	}
	break;
	case ((NI)511):
	{
		nimln_(278);		nimln_(344);		result = TM__Evu9b2R1utZubyCikahWx1g_147;
	}
	break;
	default:
	{
		nimln_(278);		nimln_(345);		result = dollar___systemZdollars_u14(code_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZhttpcore_u449)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ** dest_p0, tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
