/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@popenssl.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@popenssl.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw;
typedef struct tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
	NI32 errorCode;
};
struct tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw {
	tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA Sup;
};
typedef N_CDECL_PTR(int, tyProc__bj29cdE9aA9bshc5NUghhGaWw) (NU64 opts_p0, NU8 settings_p1);
typedef N_CDECL_PTR(int, tyProc__u0PsAQN5ndneEiWxnCoc9aw) (void);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_u193)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_u187)(void* dll_p0, NimStringV2 name_p1, NimStringV2 alternativeName_p2);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(void*, thisModule__wrappersZopenssl_u177)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u6)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void*, sslModule__wrappersZopenssl_u180)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern__pureZdynlib_u93)(NimStringV2 pattern_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3684)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_u197)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidLibrary__pureZdynlib_u9)(NCSTRING name_p0);
static N_INLINE(void*, utilModule__wrappersZopenssl_u184)(void);
static const struct {
  NI cap; NIM_CHAR data[97+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_2 = { 97 | NIM_STRLIT_FLAG, "libssl(.3|.1.1|.38|.39|.41|.43|.44|.45|.46|.47|.48|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|).dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_3 = {97, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_2};
extern TNimTypeV2 NTIv2__zLj3EiTTkXCqCx9cBzJN9bKw_;
static const struct {
  NI cap; NIM_CHAR data[122+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_4 = { 122 | NIM_STRLIT_FLAG, "Could not load SSL using libssl(.3|.1.1|.38|.39|.41|.43|.44|.45|.46|.47|.48|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|).dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_5 = {122, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_6 = { 16 | NIM_STRLIT_FLAG, "OPENSSL_init_ssl" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_7 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_9 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_10 = { 16 | NIM_STRLIT_FLAG, "SSL_library_init" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_11 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_10};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_12 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_13 = { 22 | NIM_STRLIT_FLAG, "SSL_load_error_strings" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_14 = {22, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_13};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_15 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[100+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_16 = { 100 | NIM_STRLIT_FLAG, "libcrypto(.3|.1.1|.38|.39|.41|.43|.44|.45|.46|.47|.48|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|).dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_17 = {100, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_16};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_18 = { 20 | NIM_STRLIT_FLAG, "ERR_load_BIO_strings" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_19 = {20, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_18};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_20 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_21 = { 31 | NIM_STRLIT_FLAG, "OPENSSL_add_all_algorithms_conf" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_22 = {31, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_21};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_23 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
N_LIB_PRIVATE void* thisMod__wrappersZopenssl_u179;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
N_LIB_PRIVATE void* sslMod__wrappersZopenssl_u182;
extern NIM_THREADVAR Exception* currException__system_u3651;
N_LIB_PRIVATE void* utilMod__wrappersZopenssl_u186;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, CRYPTO_malloc_init__wrappersZopenssl_u660)(void) {
	nimfr_("CRYPTO_malloc_init", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void*, thisModule__wrappersZopenssl_u177)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("thisModule", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimlf_(344, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");	{
		void* T5_;
		if (!(thisMod__wrappersZopenssl_u179 == 0)) goto LA3_;
		T5_ = (void*)0;
		T5_ = loadLib__pureZdynlib_u6();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		thisMod__wrappersZopenssl_u179 = T5_;
	}
LA3_: ;
	nimln_(346);	result = thisMod__wrappersZopenssl_u179;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_u187)(void* dll_p0, NimStringV2 name_p1, NimStringV2 alternativeName_p2) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("symNullable", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(365);	{
		if (!!((dll_p0 == 0))) goto LA3_;
		nimln_(366);		result = symAddr__pureZdynlib_u74(dll_p0, nimToCStringConv(name_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(367);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = (result == 0);
			if (!(T7_)) goto LA8_;
			T7_ = (((NI)0) < alternativeName_p2.len);
LA8_: ;
			if (!T7_) goto LA9_;
			nimln_(368);			result = symAddr__pureZdynlib_u74(dll_p0, nimToCStringConv(alternativeName_p2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA9_: ;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(370);		result = NIM_NIL;
	}
LA1_: ;
	nimln_(373);	{
		void* thisDynlib_1;
		if (!(result == 0)) goto LA14_;
		nimln_(374);		thisDynlib_1 = thisModule__wrappersZopenssl_u177();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(375);		{
			if (!(thisDynlib_1 == 0)) goto LA18_;
			nimln_(363);			nimln_(375);			result = NIM_NIL;
			goto BeforeRet_;
		}
LA18_: ;
		nimln_(376);		result = symAddr__pureZdynlib_u74(thisDynlib_1, nimToCStringConv(name_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(377);		{
			NIM_BOOL T22_;
			T22_ = (NIM_BOOL)0;
			T22_ = (result == 0);
			if (!(T22_)) goto LA23_;
			T22_ = (((NI)0) < alternativeName_p2.len);
LA23_: ;
			if (!T22_) goto LA24_;
			nimln_(378);			result = symAddr__pureZdynlib_u74(thisDynlib_1, nimToCStringConv(alternativeName_p2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA24_: ;
	}
LA14_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3684(&currException__system_u3651, (*currException__system_u3651).up, NIM_FALSE);
}
static N_INLINE(void*, sslModule__wrappersZopenssl_u180)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("sslModule", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(351);	{
		void* T6_;
		if (!(sslMod__wrappersZopenssl_u182 == 0)) goto LA4_;
		T6_ = (void*)0;
		T6_ = loadLibPattern__pureZdynlib_u93(TM__SLGpYVEqpFQ7VaPsJH6HIA_3, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		sslMod__wrappersZopenssl_u182 = T6_;
	}
LA4_: ;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		{
			tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw* T10_;
			*nimErr_ = NIM_FALSE;
			nimln_(353);			raiseDefect();
			T10_ = NIM_NIL;
			T10_ = (tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw*) nimNewObj(sizeof(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw), NIM_ALIGNOF(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw));
			(*T10_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__zLj3EiTTkXCqCx9cBzJN9bKw_);
			(*T10_).Sup.Sup.Sup.name = "LibraryError";
			(*T10_).Sup.Sup.Sup.message = TM__SLGpYVEqpFQ7VaPsJH6HIA_5;
			(*T10_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
			popCurrentException();
			raiseExceptionEx((Exception*)T10_, "LibraryError", "sslModule", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim", 353);
goto LA8_;
			popCurrentException();
			LA8_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(355);	result = sslMod__wrappersZopenssl_u182;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_u193)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("sslSymNullable", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(381);	T1_ = (void*)0;
	T1_ = sslModule__wrappersZopenssl_u180();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = symNullable__wrappersZopenssl_u187(T1_, name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_u197)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("sslSymThrows", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(384);	result = sslSymNullable__wrappersZopenssl_u193(name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(385);	{
		if (!(result == 0)) goto LA3_;
		raiseInvalidLibrary__pureZdynlib_u9(nimToCStringConv(name_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_library_init__wrappersZopenssl_u282)(void) {
	int result;
	void* newInitSym_1;
	tyProc__u0PsAQN5ndneEiWxnCoc9aw olderProc_1;
	void* T5_;
NIM_BOOL* nimErr_;
	nimfr_("SSL_library_init", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(407);	result = ((int)0);
	nimln_(408);	newInitSym_1 = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_7, TM__SLGpYVEqpFQ7VaPsJH6HIA_9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(409);	{
		tyProc__bj29cdE9aA9bshc5NUghhGaWw newInitProc_1;
		if (!!((newInitSym_1 == 0))) goto LA3_;
		nimln_(410);		newInitProc_1 = ((tyProc__bj29cdE9aA9bshc5NUghhGaWw) (newInitSym_1));
		nimln_(412);		nimln_(404);		nimln_(412);		result = newInitProc_1(0ULL, ((NU8)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(413);	T5_ = (void*)0;
	T5_ = sslSymThrows__wrappersZopenssl_u197(TM__SLGpYVEqpFQ7VaPsJH6HIA_11, TM__SLGpYVEqpFQ7VaPsJH6HIA_12);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	olderProc_1 = ((tyProc__u0PsAQN5ndneEiWxnCoc9aw) (T5_));
	nimln_(414);	{
		if (!!((olderProc_1 == 0))) goto LA8_;
		result = olderProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, SSL_load_error_strings__wrappersZopenssl_u332)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("SSL_load_error_strings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(418);	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_14, TM__SLGpYVEqpFQ7VaPsJH6HIA_15);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	nimln_(419);	{
		if (!!((theProc_1 == 0))) goto LA4_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void*, utilModule__wrappersZopenssl_u184)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("utilModule", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(359);	{
		void* T5_;
		if (!(utilMod__wrappersZopenssl_u186 == 0)) goto LA3_;
		T5_ = (void*)0;
		T5_ = loadLibPattern__pureZdynlib_u93(TM__SLGpYVEqpFQ7VaPsJH6HIA_17, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		utilMod__wrappersZopenssl_u186 = T5_;
	}
LA3_: ;
	nimln_(361);	result = utilMod__wrappersZopenssl_u186;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ERR_load_BIO_strings__wrappersZopenssl_u357)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
	void* T2_;
NIM_BOOL* nimErr_;
	nimfr_("ERR_load_BIO_strings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(422);	T1_ = (void*)0;
	T1_ = utilModule__wrappersZopenssl_u184();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (void*)0;
	T2_ = symNullable__wrappersZopenssl_u187(T1_, TM__SLGpYVEqpFQ7VaPsJH6HIA_19, TM__SLGpYVEqpFQ7VaPsJH6HIA_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T2_));
	nimln_(423);	{
		if (!!((theProc_1 == 0))) goto LA5_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, OpenSSL_add_all_algorithms__wrappersZopenssl_u377)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("OpenSSL_add_all_algorithms", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(448);	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_22, TM__SLGpYVEqpFQ7VaPsJH6HIA_23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	nimln_(449);	{
		if (!!((theProc_1 == 0))) goto LA4_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
