/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pstd@sprivate@sosfiles.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pstd@sprivate@sosfiles.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <copyfile.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyTuple__uZlLShSOvod3B0sFj1r2NQ tyTuple__uZlLShSOvod3B0sFj1r2NQ;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg;
typedef NU8 tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg;
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
typedef NU16 tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA;
typedef NU8 tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA;
struct tyTuple__uZlLShSOvod3B0sFj1r2NQ {
	NimStringV2 Field0;
	tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA Field1;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tryMoveFSObject__stdZprivateZoscommon_u86)(NimStringV2 source_p0, NimStringV2 dest_p1, NIM_BOOL isDir_p2);
N_LIB_PRIVATE N_NIMCALL(void, copyFileWithPermissions__stdZprivateZosfiles_u384)(NimStringV2 source_p0, NimStringV2 dest_p1, NIM_BOOL ignorePermissionErrors_p2, tySet_tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg options_p3);
N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringV2 source_p0, NimStringV2 dest_p1, tySet_tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg options_p2, NI bufferSize_p3);
static N_INLINE(NI, countBits32)(NU32 n_p0);
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_u26)(NU32 x_p0);
N_CDECL(int, __builtin_popcount)(unsigned int x_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nossymlinkExists)(NimStringV2 link_p0);
N_LIB_PRIVATE N_NIMCALL(void, createSymlink__stdZprivateZossymlinks_u10)(NimStringV2 src_p0, NimStringV2 dest_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, expandSymlink__stdZprivateZossymlinks_u16)(NimStringV2 symlinkPath_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZprivateZoscommon_u93)(tyTuple__UV3llMMYFckfui8YMBuUZA* x_p0);
N_LIB_PRIVATE N_NIMCALL(void, nossetFilePermissions)(NimStringV2 filename_p0, tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA permissions_p1, NIM_BOOL followSymlinks_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZprivateZosfiles_u131)(tyTuple__uZlLShSOvod3B0sFj1r2NQ x_p0);
N_LIB_PRIVATE N_NIMCALL(tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA, nosgetFilePermissions)(NimStringV2 filename_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3684)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringV2 file_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringV2 file_p0);
static const struct {
  NI cap; NIM_CHAR data[178+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_2 = { 178 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim(213, 3) `card(copyFlagSymlink * options) == 1` There should be exactly one cfSymlink* in options" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_3 = {178, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_2};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_4 = { 10 | NIM_STRLIT_FLAG, "fpUserExec" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_5 = {10, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_4};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_6 = { 11 | NIM_STRLIT_FLAG, "fpUserWrite" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_7 = {11, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_6};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_8 = { 10 | NIM_STRLIT_FLAG, "fpUserRead" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_9 = {10, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_8};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_10 = { 11 | NIM_STRLIT_FLAG, "fpGroupExec" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_11 = {11, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_10};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_12 = { 12 | NIM_STRLIT_FLAG, "fpGroupWrite" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_13 = {12, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_12};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_14 = { 11 | NIM_STRLIT_FLAG, "fpGroupRead" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_15 = {11, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_14};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_16 = { 12 | NIM_STRLIT_FLAG, "fpOthersExec" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_17 = {12, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_16};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_18 = { 13 | NIM_STRLIT_FLAG, "fpOthersWrite" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_19 = {13, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_18};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_20 = { 12 | NIM_STRLIT_FLAG, "fpOthersRead" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_21 = {12, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_20};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_22 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_23 = {0, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_22};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR Exception* currException__system_u3651;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_u26)(NU32 x_p0) {
	NI result;
	NU32 x_2;
	int T1_;
	nimfr_("countSetBitsImpl", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/countbits_impl.nim");
	result = (NI)0;
	nimlf_(67, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/countbits_impl.nim");	x_2 = x_p0;
	nimln_(72);	T1_ = (int)0;
	T1_ = __builtin_popcount(((unsigned int) (x_2)));
	result = ((NI) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(NI, countBits32)(NU32 n_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("countBits32", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/countbits_impl.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(90);	result = countSetBitsImpl__systemZcountbits95impl_u26(n_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringV2 source_p0, NimStringV2 dest_p1, tySet_tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg options_p2, NI bufferSize_p3) {
	NIM_BOOL isSymlink_1;
NIM_BOOL* nimErr_;
	nimfr_("copyFile", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(213, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");	{
		if (!!((countBits32((7 & options_p2)) == ((NI)1)))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__CMIme9a8i2wZOUbxErcFpJA_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(214);	isSymlink_1 = nossymlinkExists(source_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(215);	{
		NIM_BOOL T7_;
		NIM_BOOL T9_;
		T7_ = (NIM_BOOL)0;
		T7_ = isSymlink_1;
		if (!(T7_)) goto LA8_;
		T9_ = (NIM_BOOL)0;
		T9_ = ((options_p2 &((NU8)1<<((NU)((((tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg)2)))&7U)))!=0);
		if (T9_) goto LA10_;
		T9_ = NIM_FALSE;
LA10_: ;
		T7_ = T9_;
LA8_: ;
		if (!T7_) goto LA11_;
		nimln_(216);		goto BeforeRet_;
	}
LA11_: ;
	nimln_(223);	{
		NIM_BOOL T15_;
		NimStringV2 colontmpD_;
		T15_ = (NIM_BOOL)0;
		T15_ = isSymlink_1;
		if (!(T15_)) goto LA16_;
		T15_ = ((options_p2 &((NU8)1<<((NU)((((tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg)0)))&7U)))!=0);
LA16_: ;
		if (!T15_) goto LA17_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(224);		colontmpD_ = expandSymlink__stdZprivateZossymlinks_u16(source_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
		createSymlink__stdZprivateZossymlinks_u10(colontmpD_, dest_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
		{
			LA19_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA13_;
LA17_: ;
	{
		copyfile_state_t state_1;
		int status_1;
		int status2_1;
		nimlf_(227, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");		state_1 = copyfile_state_alloc();
		nimln_(230);		status_1 = copyfile(nimToCStringConv(source_p0), nimToCStringConv(dest_p1), state_1, COPYFILE_DATA);
		nimln_(232);		{
			NimStringV2 colontmpD__2;
			NI32 err_1;
			int T28_;
			tyTuple__UV3llMMYFckfui8YMBuUZA T29_;
			if (!!((status_1 == ((NI32)0)))) goto LA25_;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(233);			err_1 = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
			nimln_(234);			T28_ = (int)0;
			T28_ = copyfile_state_free(state_1);
			(void)(T28_);
			nimln_(235);			T29_.Field0 = source_p0;
			T29_.Field1 = dest_p1;
			colontmpD__2 = dollar___stdZprivateZoscommon_u93((&T29_));
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
			raiseOSError__stdZoserrors_u119(err_1, colontmpD__2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
			{
				LA27_:;
			}
			{
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA25_: ;
		nimlf_(236, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");		status2_1 = copyfile_state_free(state_1);
		nimln_(237);		{
			NimStringV2 colontmpD__3;
			NI32 T37_;
			tyTuple__UV3llMMYFckfui8YMBuUZA T38_;
			if (!!((status2_1 == ((NI32)0)))) goto LA34_;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			T37_ = (NI32)0;
			T37_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			T38_.Field0 = source_p0;
			T38_.Field1 = dest_p1;
			colontmpD__3 = dollar___stdZprivateZoscommon_u93((&T38_));
			if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			raiseOSError__stdZoserrors_u119(T37_, colontmpD__3);
			if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			{
				LA36_:;
			}
			{
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA34_: ;
	}
LA13_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZprivateZosfiles_u27)(tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)0):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_5;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)1):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_7;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)2):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_9;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)3):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_11;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)4):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_13;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)5):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_15;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)6):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_17;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)7):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_19;
	}
	break;
	case ((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)8):
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_21;
	}
	break;
	default:
	{
		result = TM__CMIme9a8i2wZOUbxErcFpJA_23;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nossetFilePermissions)(NimStringV2 filename_p0, tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA permissions_p1, NIM_BOOL followSymlinks_p2) {
	mode_t p_1;
NIM_BOOL* nimErr_;
	nimfr_("setFilePermissions", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(113, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");	p_1 = ((mode_t)0);
	nimln_(114);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)2)))&15U)))!=0)) goto LA3_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IRUSR)));
	}
LA3_: ;
	nimln_(115);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)1)))&15U)))!=0)) goto LA7_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IWUSR)));
	}
LA7_: ;
	nimln_(116);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)0)))&15U)))!=0)) goto LA11_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IXUSR)));
	}
LA11_: ;
	nimln_(118);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)5)))&15U)))!=0)) goto LA15_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IRGRP)));
	}
LA15_: ;
	nimln_(119);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)4)))&15U)))!=0)) goto LA19_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IWGRP)));
	}
LA19_: ;
	nimln_(120);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)3)))&15U)))!=0)) goto LA23_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IXGRP)));
	}
LA23_: ;
	nimln_(122);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)8)))&15U)))!=0)) goto LA27_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IROTH)));
	}
LA27_: ;
	nimln_(123);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)7)))&15U)))!=0)) goto LA31_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IWOTH)));
	}
LA31_: ;
	nimln_(124);	{
		if (!((permissions_p1 &((NU16)1<<((NU)((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)6)))&15U)))!=0)) goto LA35_;
		p_1 = (NU16)(p_1 | ((mode_t) (S_IXOTH)));
	}
LA35_: ;
	nimln_(126);	{
		NIM_BOOL T39_;
		T39_ = (NIM_BOOL)0;
		T39_ = !(followSymlinks_p2);
		if (!(T39_)) goto LA40_;
		T39_ = nossymlinkExists(filename_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
LA40_: ;
		if (!T39_) goto LA41_;
		nimln_(128);		{
			int T45_;
			NimStringV2 colontmpD_;
			NI32 T49_;
			tyTuple__uZlLShSOvod3B0sFj1r2NQ T50_;
			T45_ = (int)0;
			T45_ = lchmod(nimToCStringConv(filename_p0), ((mode_t) (p_1)));
			if (!!((T45_ == ((NI32)0)))) goto LA46_;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			nimln_(129);			T49_ = (NI32)0;
			T49_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
			T50_.Field0 = filename_p0;
			T50_.Field1 = permissions_p1;
			colontmpD_ = dollar___stdZprivateZosfiles_u131(T50_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
			raiseOSError__stdZoserrors_u119(T49_, colontmpD_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
			{
				LA48_:;
			}
			{
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA46_: ;
	}
	goto LA37_;
LA41_: ;
	{
		nimlf_(131, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");		{
			int T56_;
			NimStringV2 colontmpD__2;
			NI32 T60_;
			tyTuple__uZlLShSOvod3B0sFj1r2NQ T61_;
			T56_ = (int)0;
			T56_ = chmod(nimToCStringConv(filename_p0), ((mode_t) (p_1)));
			if (!!((T56_ == ((NI32)0)))) goto LA57_;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(132);			T60_ = (NI32)0;
			T60_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto LA59_;
			T61_.Field0 = filename_p0;
			T61_.Field1 = permissions_p1;
			colontmpD__2 = dollar___stdZprivateZosfiles_u131(T61_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA59_;
			raiseOSError__stdZoserrors_u119(T60_, colontmpD__2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA59_;
			{
				LA59_:;
			}
			{
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA57_: ;
	}
LA37_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA, nosgetFilePermissions)(NimStringV2 filename_p0) {
	tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA result;
	struct stat a_1;
NIM_BOOL* nimErr_;
	nimfr_("getFilePermissions", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA));
	nimZeroMem((void*)(&a_1), sizeof(struct stat));
	nimlf_(71, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = stat(nimToCStringConv(filename_p0), (&a_1));
		if (!(T3_ < ((NI32)0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T6_, filename_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(72);	result = 0;
	nimln_(73);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IRUSR))) == ((mode_t)0)))) goto LA9_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)2))) & 15);
	}
LA9_: ;
	nimln_(74);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IWUSR))) == ((mode_t)0)))) goto LA13_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)1))) & 15);
	}
LA13_: ;
	nimln_(75);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IXUSR))) == ((mode_t)0)))) goto LA17_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)0))) & 15);
	}
LA17_: ;
	nimln_(77);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IRGRP))) == ((mode_t)0)))) goto LA21_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)5))) & 15);
	}
LA21_: ;
	nimln_(78);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IWGRP))) == ((mode_t)0)))) goto LA25_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)4))) & 15);
	}
LA25_: ;
	nimln_(79);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IXGRP))) == ((mode_t)0)))) goto LA29_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)3))) & 15);
	}
LA29_: ;
	nimln_(81);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IROTH))) == ((mode_t)0)))) goto LA33_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)8))) & 15);
	}
LA33_: ;
	nimln_(82);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IWOTH))) == ((mode_t)0)))) goto LA37_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)7))) & 15);
	}
LA37_: ;
	nimln_(83);	{
		if (!!(((NU16)(a_1.st_mode & ((mode_t) (S_IXOTH))) == ((mode_t)0)))) goto LA41_;
		result |= ((NU16)1)<<(((((tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA)6))) & 15);
	}
LA41_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3684(&currException__system_u3651, (*currException__system_u3651).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(void, copyFileWithPermissions__stdZprivateZosfiles_u384)(NimStringV2 source_p0, NimStringV2 dest_p1, NIM_BOOL ignorePermissionErrors_p2, tySet_tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg options_p3) {
	tySet_tyEnum_FilePermission__QEvs0LW7Ocq3P9cIpD4G0YA T2_;
NIM_BOOL* nimErr_;
	nimfr_("copyFileWithPermissions", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimln_(316);	noscopyFile(source_p0, dest_p1, options_p3, ((NI)16384));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(319);	T2_ = nosgetFilePermissions(source_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(320);	nimln_(319);	nossetFilePermissions(dest_p1, T2_, ((options_p3 &((NU8)1<<((NU)((((tyEnum_CopyFlag__7R6qcZTY5blnZkENr1u1eg)1)))&7U)))!=0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		{
			*nimErr_ = NIM_FALSE;
			nimln_(322);			raiseDefect();
			{
				if (!!(ignorePermissionErrors_p2)) goto LA8_;
				nimln_(323);				reraiseException();
goto LA4_;
			}
LA8_: ;
			popCurrentException();
			LA4_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringV2 file_p0) {
	NIM_BOOL result;
	nimfr_("tryRemoveFile", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");
	nimln_(352);	result = NIM_TRUE;
	nimln_(365);	{
		NIM_BOOL T3_;
		int T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (int)0;
		T4_ = unlink(nimToCStringConv(file_p0));
		T3_ = !((T4_ == ((NI32)0)));
		if (!(T3_)) goto LA5_;
		T3_ = !((errno == ENOENT));
LA5_: ;
		if (!T3_) goto LA6_;
		nimln_(366);		result = NIM_FALSE;
	}
LA6_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringV2 file_p0) {
NIM_BOOL* nimErr_;
	nimfr_("removeFile", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimln_(382);	{
		NIM_BOOL T3_;
		NI32 T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = nostryRemoveFile(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		nimln_(383);		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T6_, file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, nosmoveFile)(NimStringV2 source_p0, NimStringV2 dest_p1) {
NIM_BOOL* nimErr_;
	nimfr_("moveFile", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimln_(404);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = tryMoveFSObject__stdZprivateZoscommon_u86(source_p0, dest_p1, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		nimln_(409);		copyFileWithPermissions__stdZprivateZosfiles_u384(source_p0, dest_p1, NIM_TRUE, 1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(411);		nosremoveFile(source_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		if (NIM_UNLIKELY(*nimErr_)) {
			LA6_:;
			{
				NIM_BOOL T10_;
				*nimErr_ = NIM_FALSE;
				nimln_(413);				raiseDefect();
				T10_ = (NIM_BOOL)0;
				T10_ = nostryRemoveFile(dest_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				(void)(T10_);
				nimln_(414);				reraiseException();
goto LA8_;
				popCurrentException();
				LA8_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
