/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pstd@sobjectdollar.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pstd@sobjectdollar.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__pureZasyncfutures_u340)(NimStringV2* s_p0, NCSTRING x_p1);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__pureZstrutils_u1425)(NimStringV2* s_p0, NI x_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_2 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_3 = {1, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_4 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_5 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_6 = { 8 | NIM_STRLIT_FLAG, "procname" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_7 = {8, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_8 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_9 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_8};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_10 = { 3 | NIM_STRLIT_FLAG, "nil" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_11 = {3, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_10};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_12 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_13 = { 4 | NIM_STRLIT_FLAG, "line" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_14 = {4, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_13};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_15 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_8};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_16 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_17 = { 8 | NIM_STRLIT_FLAG, "filename" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_18 = {8, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_17};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_19 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_8};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_20 = {3, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_21 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_22 = {1, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_21};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZasyncfutures_u314)(tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ x_p0) {
	NimStringV2 result;
	NI countX60gensym5__1;
	nimfr_("$", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/objectdollar.nim");
	nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/objectdollar.nim");	nimlf_(25, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/miscdollars.nim");	result = TM__US7tUPSVHwyWbwv9cB5DrpQ_3;
	nimln_(27);	countX60gensym5__1 = ((NI)0);
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(29);		{
			if (!(((NI)0) < countX60gensym5__1)) goto LA7_;
			prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_5);
		}
LA7_: ;
		nimln_(31);		prepareAdd((&result), 8);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_7);
		nimln_(32);		prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_9);
		nimln_(33);		countX60gensym5__1 += ((NI)1);
		nimln_(36);		{
			if (!(x_p0.procname == 0)) goto LA11_;
			prepareAdd((&result), 3);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_11);
		}
		goto LA9_;
LA11_: ;
		{
			nimln_(37);			addQuoted__pureZasyncfutures_u340((&result), x_p0.procname);
		}
LA9_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA16_;
		nimln_(29);		{
			if (!(((NI)0) < countX60gensym5__1)) goto LA20_;
			prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_12);
		}
LA20_: ;
		nimln_(31);		prepareAdd((&result), 4);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_14);
		nimln_(32);		prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_15);
		nimln_(33);		countX60gensym5__1 += ((NI)1);
		nimln_(39);		addQuoted__pureZstrutils_u1425((&result), x_p0.line);
	}
LA16_: ;
	{
		if (!NIM_TRUE) goto LA24_;
		nimln_(29);		{
			if (!(((NI)0) < countX60gensym5__1)) goto LA28_;
			prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_16);
		}
LA28_: ;
		nimln_(31);		prepareAdd((&result), 8);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_18);
		nimln_(32);		prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_19);
		nimln_(33);		countX60gensym5__1 += ((NI)1);
		nimln_(36);		{
			if (!(x_p0.filename == 0)) goto LA32_;
			prepareAdd((&result), 3);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_20);
		}
		goto LA30_;
LA32_: ;
		{
			nimln_(37);			addQuoted__pureZasyncfutures_u340((&result), x_p0.filename);
		}
LA30_: ;
	}
LA24_: ;
	nimln_(45);	prepareAdd((&result), 1);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_22);
	popFrame();
	return result;
}
