/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@psystem@sexceptions.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@psystem@sexceptions.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ;
typedef struct tyObject_ArithmeticDefect__8pyQ21EwraK7FnX18lAGYQ tyObject_ArithmeticDefect__8pyQ21EwraK7FnX18lAGYQ;
typedef struct tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg;
typedef struct tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA;
typedef struct tyTuple__TGoPjOunaLBwuXSEEclIhw tyTuple__TGoPjOunaLBwuXSEEclIhw;
typedef struct tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g;
typedef struct tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA;
typedef struct tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw;
typedef struct tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg;
typedef struct tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew;
typedef struct tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w;
typedef struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ;
typedef struct tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA;
typedef struct tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA;
typedef struct tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ;
typedef struct tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA;
typedef struct tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__8pyQ21EwraK7FnX18lAGYQ {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ {
	tyObject_ArithmeticDefect__8pyQ21EwraK7FnX18lAGYQ Sup;
};
struct tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA {
	NI len;
	NI cap;
	tyTuple__TGoPjOunaLBwuXSEEclIhw* d;
};
struct tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg {
	tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw traceStack;
	tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
	NI32 errorCode;
};
struct tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw {
	tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA Sup;
};
struct tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA {
	tyObject_ArithmeticDefect__8pyQ21EwraK7FnX18lAGYQ Sup;
};
struct tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ {
	tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ Sup;
};
struct tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4590)(tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3520)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5063)(tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3722)(tySequence__qs2FgbZ9c9aoxerHPHQd5foQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5075)(tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3041)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3049)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4602)(tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4659)(tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4671)(tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZdynlib_u15)(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZdynlib_u27)(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4882)(tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4894)(tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u72)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9192)(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9204)(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u74)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4749)(tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4761)(tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u76)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u78)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5129)(tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5141)(tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u80)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4336)(tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4348)(tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u82)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u1134)(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZhttpcore_u1146)(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u84)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZtypedthreads_u220)(tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZtypedthreads_u232)(tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u86)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4986)(tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4998)(tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__B9bQ8xGIJLaZfdGNMDF25Mw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__kNz9aydm5M22aRCRZAHmADQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__eTMcw3ECphD03F8Qc5XW5g_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__m7fPxdGL9c9ayLn0ZHxY9c0wA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__zLj3EiTTkXCqCx9cBzJN9bKw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__qz4jKr6ntUCOLnyn4vvwOA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Au49bMGi5bVJVUPJnYnTWwg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__OefSIx6jC6YPnq9aG8TlFew_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Am0uv9aj3OA9cU0B2IRZQn1w_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__NrH9bj0l61WQ9aofL9ag1derA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__twMj9a6pYydBV9cthqcvNwIA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Y3ufay6FmFw9cy5zoiKiFaQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__3KLfkUzkFiflaclbZoLhpA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__3qKwUoIivhPaX9aWgAFm1mw_;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[5] = {3701606400, 1285336064, 1879817216, 2626738944, 3707619584};
N_LIB_PRIVATE TNimTypeV2 NTIv2__kNz9aydm5M22aRCRZAHmADQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u58, .size = sizeof(tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)eqtrace___system_u5075, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 1879817216, 3829187584};
N_LIB_PRIVATE TNimTypeV2 NTIv2__B9bQ8xGIJLaZfdGNMDF25Mw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u4602, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 1879817216, 857522944};
N_LIB_PRIVATE TNimTypeV2 NTIv2__eTMcw3ECphD03F8Qc5XW5g_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)eqtrace___system_u4671, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 1879817216, 3083846912};
N_LIB_PRIVATE TNimTypeV2 NTIv2__m7fPxdGL9c9ayLn0ZHxY9c0wA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___stdZassertions_u49, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[5] = {3701606400, 1285336064, 1493325056, 1042491904, 3103199744};
N_LIB_PRIVATE TNimTypeV2 NTIv2__zLj3EiTTkXCqCx9cBzJN9bKw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u66, .size = sizeof(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw), .align = (NI16) NIM_ALIGNOF(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___pureZdynlib_u27, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 1493325056, 1042491904};
N_LIB_PRIVATE TNimTypeV2 NTIv2__qz4jKr6ntUCOLnyn4vvwOA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u68, .size = sizeof(tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA), .align = (NI16) NIM_ALIGNOF(tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___stdZoserrors_u72, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[4] = {3701606400, 1285336064, 1879817216, 3997052928};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Au49bMGi5bVJVUPJnYnTWwg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u70, .size = sizeof(tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg), .align = (NI16) NIM_ALIGNOF(tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_8, .traceImpl = (void*)eqtrace___system_u4894, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[4] = {3701606400, 1285336064, 1493325056, 3889308416};
N_LIB_PRIVATE TNimTypeV2 NTIv2__OefSIx6jC6YPnq9aG8TlFew_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u72, .size = sizeof(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_9, .traceImpl = (void*)eqtrace___system_u9204, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_10[4] = {3701606400, 1285336064, 1879817216, 1831780096};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Am0uv9aj3OA9cU0B2IRZQn1w_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u74, .size = sizeof(tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w), .align = (NI16) NIM_ALIGNOF(tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_10, .traceImpl = (void*)eqtrace___system_u4761, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_11[4] = {3701606400, 1285336064, 1493325056, 659692032};
N_LIB_PRIVATE TNimTypeV2 NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u76, .size = sizeof(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), .align = (NI16) NIM_ALIGNOF(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_11, .traceImpl = (void*)eqtrace___pureZparseutils_u342, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_12[5] = {3701606400, 1285336064, 1879817216, 2626738944, 2986249984};
N_LIB_PRIVATE TNimTypeV2 NTIv2__NrH9bj0l61WQ9aofL9ag1derA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u78, .size = sizeof(tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_12, .traceImpl = (void*)eqtrace___system_u5141, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_13[4] = {3701606400, 1285336064, 1879817216, 52688640};
N_LIB_PRIVATE TNimTypeV2 NTIv2__twMj9a6pYydBV9cthqcvNwIA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u80, .size = sizeof(tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA), .align = (NI16) NIM_ALIGNOF(tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_13, .traceImpl = (void*)eqtrace___system_u4348, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_14[5] = {3701606400, 1285336064, 1493325056, 659692032, 2074045184};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Y3ufay6FmFw9cy5zoiKiFaQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u82, .size = sizeof(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ), .align = (NI16) NIM_ALIGNOF(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_14, .traceImpl = (void*)eqtrace___pureZhttpcore_u1146, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_15[4] = {3701606400, 1285336064, 1493325056, 2732560640};
N_LIB_PRIVATE TNimTypeV2 NTIv2__3KLfkUzkFiflaclbZoLhpA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u84, .size = sizeof(tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA), .align = (NI16) NIM_ALIGNOF(tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_15, .traceImpl = (void*)eqtrace___stdZtypedthreads_u232, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_16[4] = {3701606400, 1285336064, 1879817216, 2729464320};
N_LIB_PRIVATE TNimTypeV2 NTIv2__3qKwUoIivhPaX9aWgAFm1mw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u86, .size = sizeof(tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw), .align = (NI16) NIM_ALIGNOF(tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_16, .traceImpl = (void*)eqtrace___system_u4998, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5063)(tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5063(((tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimln_(360);	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3041)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3049(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(138, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg*) (env_p1));
		nimln_(141);		add__system_u3041((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5075)(tyObject_OverflowDefect__kNz9aydm5M22aRCRZAHmADQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimlf_(521, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3520(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4590)(tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4590(((tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4602)(tyObject_RangeDefect__B9bQ8xGIJLaZfdGNMDF25Mw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4659)(tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4659(((tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4671)(tyObject_IndexDefect__eTMcw3ECphD03F8Qc5XW5g* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZassertions_u37(((tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__m7fPxdGL9c9ayLn0ZHxY9c0wA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZdynlib_u15)(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZdynlib_u15(((tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZdynlib_u27)(tyObject_LibraryError__zLj3EiTTkXCqCx9cBzJN9bKw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZoserrors_u60(((tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__qz4jKr6ntUCOLnyn4vvwOA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4882)(tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4882(((tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4894)(tyObject_ObjectConversionDefect__Au49bMGi5bVJVUPJnYnTWwg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9192)(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u72)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u9192(((tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9204)(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4749)(tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u74)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4749(((tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4761)(tyObject_FieldDefect__Am0uv9aj3OA9cU0B2IRZQn1w* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u76)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZparseutils_u330(((tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5129)(tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u78)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5129(((tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5141)(tyObject_DivByZeroDefect__NrH9bj0l61WQ9aofL9ag1derA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4336)(tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u80)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4336(((tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4348)(tyObject_ReraiseDefect__twMj9a6pYydBV9cthqcvNwIA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u1134)(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u82)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZhttpcore_u1134(((tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZhttpcore_u1146)(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZtypedthreads_u220)(tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u84)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZtypedthreads_u220(((tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZtypedthreads_u232)(tyObject_ResourceExhaustedError__3KLfkUzkFiflaclbZoLhpA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4986)(tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u86)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4986(((tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4998)(tyObject_NilAccessDefect__3qKwUoIivhPaX9aWgAFm1mw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
