/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pterminal.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@pterminal.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_PTerminalcolonObjectType___kYmINg7Hb5HWT9b8bLKZCAQ tyObject_PTerminalcolonObjectType___kYmINg7Hb5HWT9b8bLKZCAQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NU8 tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_BackgroundColor__DutXSJ9ceIlSbLAk2ykPnkQ;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, ansiStyleCode__pureZterminal_u373)(NI style_p0);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZparsecfg_u356)(NimStringV2* result_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZparsecfg_u369)(NimStringV2* result_p0, NI value_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_3 = { 2 | NIM_STRLIT_FLAG, "\033[" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_4 = {2, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_5 = { 1 | NIM_STRLIT_FLAG, "m" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_6 = {1, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_5};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_8 = { 4 | NIM_STRLIT_FLAG, "\033[0m" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_9 = {4, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_8};
N_LIB_PRIVATE NIM_THREADVAR tyObject_PTerminalcolonObjectType___kYmINg7Hb5HWT9b8bLKZCAQ* gTerm__pureZterminal_u10;
N_LIB_PRIVATE NIM_THREADVAR NI gFG__pureZterminal_u356;
N_LIB_PRIVATE NIM_THREADVAR NI gBG__pureZterminal_u357;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, ansiStyleCode__pureZterminal_u373)(NI style_p0) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("ansiStyleCode", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		NimStringV2 fmtRes_1;
		fmtRes_1.len = 0; fmtRes_1.p = NIM_NIL;
		nimlf_(653, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strformat.nim");		nimlf_(632, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");		fmtRes_1 = rawNewString(((NI)41));
		formatValue__pureZparsecfg_u356((&fmtRes_1), TM__CN3raB9atujkEiPpxYAdlgQ_4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		formatValue__pureZparsecfg_u369((&fmtRes_1), style_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		prepareAdd((&fmtRes_1), 1);
appendString((&fmtRes_1), TM__CN3raB9atujkEiPpxYAdlgQ_6);
		nimlf_(653, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strformat.nim");		result = fmtRes_1;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor__pureZterminal_u493)(FILE* f_p0, tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg fg_p1, NIM_BOOL bright_p2) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("setForegroundColor", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(726, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");	gFG__pureZterminal_u356 = fg_p1;
	nimln_(727);	{
		NI TM__CN3raB9atujkEiPpxYAdlgQ_2;
		if (!bright_p2) goto LA4_;
		if (nimAddInt(gFG__pureZterminal_u356, ((NI)60), &TM__CN3raB9atujkEiPpxYAdlgQ_2)) { raiseOverflow(); goto LA1_;
		};
		gFG__pureZterminal_u356 = (NI)(TM__CN3raB9atujkEiPpxYAdlgQ_2);
	}
LA4_: ;
	nimln_(728);	colontmpD_ = ansiStyleCode__pureZterminal_u373(gFG__pureZterminal_u356);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	write__stdZsyncio_u254(f_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setBackgroundColor__pureZterminal_u506)(FILE* f_p0, tyEnum_BackgroundColor__DutXSJ9ceIlSbLAk2ykPnkQ bg_p1, NIM_BOOL bright_p2) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("setBackgroundColor", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(755, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");	gBG__pureZterminal_u357 = bg_p1;
	nimln_(756);	{
		NI TM__CN3raB9atujkEiPpxYAdlgQ_7;
		if (!bright_p2) goto LA4_;
		if (nimAddInt(gBG__pureZterminal_u357, ((NI)60), &TM__CN3raB9atujkEiPpxYAdlgQ_7)) { raiseOverflow(); goto LA1_;
		};
		gBG__pureZterminal_u357 = (NI)(TM__CN3raB9atujkEiPpxYAdlgQ_7);
	}
LA4_: ;
	nimln_(757);	colontmpD_ = ansiStyleCode__pureZterminal_u373(gBG__pureZterminal_u357);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	write__stdZsyncio_u254(f_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes__pureZterminal_u358)(FILE* f_p0) {
NIM_BOOL* nimErr_;
	nimfr_("resetAttributes", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(615, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");	write__stdZsyncio_u254(f_p0, TM__CN3raB9atujkEiPpxYAdlgQ_9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(616);	gFG__pureZterminal_u356 = ((NI)0);
	nimln_(617);	gBG__pureZterminal_u357 = ((NI)0);
	}BeforeRet_: ;
	popFrame();
}
