/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@ptiara@score.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@ptiara@score.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, escapeHtml__OOZOOZsrcZtiaraZbuilder_u28)(NimStringV2 value_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NimStringV2, dollar___OOZOOZsrcZtiaraZbuilder_u4)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHtmlStr__OOZOOZsrcZtiaraZcore_u4)(NimStringV2 x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toHtmlStr", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/core.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = escapeHtml__OOZOOZsrcZtiaraZbuilder_u28(x_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, dollar___OOZOOZsrcZtiaraZbuilder_u4)(NimStringV2 value_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	nimfr_("$", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(7, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD_ = eqdup___system_u2728(value_p0);
	result = colontmpD_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHtmlStr__OOZOOZsrcZtiaraZcore_u7)(NimStringV2 x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toHtmlStr", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/core.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = dollar___OOZOOZsrcZtiaraZbuilder_u4(x_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHtmlStr__OOZOOZsrcZtiaraZcore_u10)(NI x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toHtmlStr", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/core.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = dollar___systemZdollars_u14(x_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
