/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@ptiara@scomponents@spageHeading.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@ptiara@scomponents@spageHeading.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  NI len; tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content { NI cap; tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, el__OOZOOZsrcZtiaraZbuilder_u563)(NimStringV2 name_p0, NimStringV2 body_p1, tyTuple__UV3llMMYFckfui8YMBuUZA* attrs_p2, NI attrs_p2Len_0);
static N_INLINE(NimStringV2, textNode__OOZOOZsrcZtiaraZbuilder_u32)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, escapeHtml__OOZOOZsrcZtiaraZbuilder_u28)(NimStringV2 value_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__OOZsrcZappZviewsZhome_u57)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZenvvars_u103)(tySequence__4eQHGndY6XBYpFOH09apV8Q dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, joinHtml__OOZOOZsrcZtiaraZbuilder_u575)(NimStringV2* parts_p0, NI parts_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
static N_INLINE(NimStringV2, dollar___OOZOOZsrcZtiaraZbuilder_u4)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q, mergeAttrs__OOZOOZsrcZtiaraZcomponentsZutils_u5)(tyTuple__UV3llMMYFckfui8YMBuUZA* baseAttrs_p0, NI baseAttrs_p0Len_0, tySequence__4eQHGndY6XBYpFOH09apV8Q extraAttrs_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZappZviewsZhome_u176)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_2 = { 2 | NIM_STRLIT_FLAG, "h2" };
static const NimStringV2 TM__lD41XyXeh49b9blYgEzMSLeQ_3 = {2, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_5 = { 5 | NIM_STRLIT_FLAG, "class" };
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_6 = { 18 | NIM_STRLIT_FLAG, "page-heading-title" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_7 = { 1 | NIM_STRLIT_FLAG, "p" };
static const NimStringV2 TM__lD41XyXeh49b9blYgEzMSLeQ_8 = {1, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_7};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_10 = { 24 | NIM_STRLIT_FLAG, "page-heading-description" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_11 = { 3 | NIM_STRLIT_FLAG, "div" };
static const NimStringV2 TM__lD41XyXeh49b9blYgEzMSLeQ_12 = {3, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_11};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_14 = { 17 | NIM_STRLIT_FLAG, "page-heading-copy" };
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__lD41XyXeh49b9blYgEzMSLeQ_15 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__lD41XyXeh49b9blYgEzMSLeQ_16 = {3, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_11};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_18 = { 20 | NIM_STRLIT_FLAG, "page-heading-actions" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_19 = { 6 | NIM_STRLIT_FLAG, "header" };
static const NimStringV2 TM__lD41XyXeh49b9blYgEzMSLeQ_20 = {6, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_19};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_22 = { 12 | NIM_STRLIT_FLAG, "page-heading" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__lD41XyXeh49b9blYgEzMSLeQ_24 = { 10 | NIM_STRLIT_FLAG, "data-tiara" };
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__lD41XyXeh49b9blYgEzMSLeQ_4 = {{5, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_5},
{18, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_6}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__lD41XyXeh49b9blYgEzMSLeQ_9 = {{5, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_5},
{24, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_10}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__lD41XyXeh49b9blYgEzMSLeQ_13 = {{5, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_5},
{17, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_14}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__lD41XyXeh49b9blYgEzMSLeQ_17 = {{5, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_5},
{20, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_18}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__lD41XyXeh49b9blYgEzMSLeQ_21 = {{5, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_5},
{12, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_22}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__lD41XyXeh49b9blYgEzMSLeQ_23 = {{10, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_24},
{12, (NimStrPayload*)&TM__lD41XyXeh49b9blYgEzMSLeQ_22}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NimStringV2, textNode__OOZOOZsrcZtiaraZbuilder_u32)(NimStringV2 value_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("textNode", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(30, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");	result = escapeHtml__OOZOOZsrcZtiaraZbuilder_u28(value_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	popFrame();
}
static N_INLINE(NimStringV2, dollar___OOZOOZsrcZtiaraZbuilder_u4)(NimStringV2 value_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	nimfr_("$", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(7);	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD_ = eqdup___system_u2728(value_p0);
	result = colontmpD_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, pageHeading__OOZOOZexamplesZpreview_u920)(NimStringV2 title_p1, NimStringV2 description_p2, NimStringV2 actions_p3, tySequence__4eQHGndY6XBYpFOH09apV8Q attrs_p4) {
	NimStringV2 result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ copyBlocks_1;
	NimStringV2 colontmpD_;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__2;
	NimStringV2 headingBlock_1;
	NimStringV2 colontmpD__3;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__4;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ innerParts_1;
	NimStringV2 colontmpD__5;
	NimStringV2 colontmpD__6;
	NimStringV2 colontmpD__7;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__8;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__9;
	NimStringV2 T1_;
	NimStringV2 blitTmp_1;
NIM_BOOL* nimErr_;
	nimfr_("pageHeading", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/pageHeading.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	copyBlocks_1.len = 0; copyBlocks_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	headingBlock_1.len = 0; headingBlock_1.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	innerParts_1.len = 0; innerParts_1.p = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
	colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
	colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
	nimlf_(13, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/pageHeading.nim");	copyBlocks_1.len = 1; copyBlocks_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimln_(14);	colontmpD_ = textNode__OOZOOZsrcZtiaraZbuilder_u32(title_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD__2.len = 1; colontmpD__2.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(1, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
	colontmpD__2.p->data[0] = TM__lD41XyXeh49b9blYgEzMSLeQ_4;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__lD41XyXeh49b9blYgEzMSLeQ_3, colontmpD_, ((colontmpD__2).p) ? (colontmpD__2.p->data) : NIM_NIL, colontmpD__2.len);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T1_); goto BeforeRet_;}
	copyBlocks_1.p->data[0] = T1_;
	nimln_(16);	{
		NimStringV2 colontmpD__10;
		tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__11;
		NimStringV2 T6_;
		if (!(((NI)0) < description_p2.len)) goto LA4_;
		colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
		colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
		nimln_(17);		colontmpD__10 = textNode__OOZOOZsrcZtiaraZbuilder_u32(description_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__11.len = 1; colontmpD__11.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(1, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
		colontmpD__11.p->data[0] = TM__lD41XyXeh49b9blYgEzMSLeQ_9;
		T6_.len = 0; T6_.p = NIM_NIL;
		T6_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__lD41XyXeh49b9blYgEzMSLeQ_8, colontmpD__10, ((colontmpD__11).p) ? (colontmpD__11.p->data) : NIM_NIL, colontmpD__11.len);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T6_); goto BeforeRet_;}
		add__OOZsrcZappZviewsZhome_u57((&copyBlocks_1), T6_);
		nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");		eqdestroy___stdZenvvars_u103(colontmpD__11);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
	}
LA4_: ;
	nimlf_(19, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/pageHeading.nim");	nimln_(21);	colontmpD__3 = joinHtml__OOZOOZsrcZtiaraZbuilder_u575(((copyBlocks_1).p) ? (copyBlocks_1.p->data) : NIM_NIL, copyBlocks_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(22);	colontmpD__4.len = 1; colontmpD__4.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(1, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
	colontmpD__4.p->data[0] = TM__lD41XyXeh49b9blYgEzMSLeQ_13;
	nimln_(19);	headingBlock_1 = el__OOZOOZsrcZtiaraZbuilder_u563(TM__lD41XyXeh49b9blYgEzMSLeQ_12, colontmpD__3, ((colontmpD__4).p) ? (colontmpD__4.p->data) : NIM_NIL, colontmpD__4.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(24);	innerParts_1.len = 1; innerParts_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	blitTmp_1 = headingBlock_1;
	innerParts_1.p->data[0] = blitTmp_1;
	nimln_(25);	{
		tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__12;
		NimStringV2 T11_;
		colontmpD__5 = dollar___OOZOOZsrcZtiaraZbuilder_u4(actions_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__6 = nsuStrip(colontmpD__5, NIM_TRUE, NIM_TRUE, TM__lD41XyXeh49b9blYgEzMSLeQ_15);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(((NI)0) < colontmpD__6.len)) goto LA9_;
		colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
		nimln_(26);		colontmpD__12.len = 1; colontmpD__12.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(1, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
		colontmpD__12.p->data[0] = TM__lD41XyXeh49b9blYgEzMSLeQ_17;
		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__lD41XyXeh49b9blYgEzMSLeQ_16, actions_p3, ((colontmpD__12).p) ? (colontmpD__12.p->data) : NIM_NIL, colontmpD__12.len);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T11_); goto BeforeRet_;}
		add__OOZsrcZappZviewsZhome_u57((&innerParts_1), T11_);
		nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");		eqdestroy___stdZenvvars_u103(colontmpD__12);
	}
LA9_: ;
	nimlf_(5, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/pageHeading.nim");	nimln_(28);	nimln_(30);	colontmpD__7 = joinHtml__OOZOOZsrcZtiaraZbuilder_u575(((innerParts_1).p) ? (innerParts_1.p->data) : NIM_NIL, innerParts_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(31);	colontmpD__8.len = 2; colontmpD__8.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(2, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
	colontmpD__8.p->data[0] = TM__lD41XyXeh49b9blYgEzMSLeQ_21;
	colontmpD__8.p->data[1] = TM__lD41XyXeh49b9blYgEzMSLeQ_23;
	colontmpD__9 = mergeAttrs__OOZOOZsrcZtiaraZcomponentsZutils_u5(((colontmpD__8).p) ? (colontmpD__8.p->data) : NIM_NIL, colontmpD__8.len, attrs_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(28);	result = el__OOZOOZsrcZtiaraZbuilder_u563(TM__lD41XyXeh49b9blYgEzMSLeQ_20, colontmpD__7, ((colontmpD__9).p) ? (colontmpD__9.p->data) : NIM_NIL, colontmpD__9.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");	eqdestroy___stdZenvvars_u103(colontmpD__9);
	eqdestroy___stdZenvvars_u103(colontmpD__8);
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
	if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
	if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
	nimlf_(22, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/navbar.nim");	eqdestroy___OOZsrcZappZviewsZhome_u176(innerParts_1);
	nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");	eqdestroy___stdZenvvars_u103(colontmpD__4);
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
	nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");	eqdestroy___stdZenvvars_u103(colontmpD__2);
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	nimlf_(22, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/navbar.nim");	eqdestroy___OOZsrcZappZviewsZhome_u176(copyBlocks_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
