/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/tiara/website/.crown -o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@ptiara@scomponents@scarousel.nim.c.o /Users/nakagawa_shota/repo/valit/tiara/website/nimcache/@ptiara@scomponents@scarousel.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  NI len; tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
typedef NimStringV2 tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ[2];
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content { NI cap; tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizeDomId__OOZOOZsrcZtiaraZcomponentsZutils_u139)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__OOZsrcZappZviewsZhome_u57)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, el__OOZOOZsrcZtiaraZbuilder_u563)(NimStringV2 name_p0, NimStringV2 body_p1, tyTuple__UV3llMMYFckfui8YMBuUZA* attrs_p2, NI attrs_p2Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2722)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZenvvars_u103)(tySequence__4eQHGndY6XBYpFOH09apV8Q dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, text__OOZOOZexamplesZpreview_u57)(NimStringV2 content_p1, NimStringV2 tag_p2, tySequence__4eQHGndY6XBYpFOH09apV8Q attrs_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, joinHtml__OOZOOZsrcZtiaraZbuilder_u575)(NimStringV2* parts_p0, NI parts_p0Len_0);
static N_INLINE(NimStringV2, textNode__OOZOOZsrcZtiaraZbuilder_u32)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, escapeHtml__OOZOOZsrcZtiaraZbuilder_u28)(NimStringV2 value_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
static N_INLINE(NimStringV2, rawHtml__OOZOOZsrcZtiaraZbuilder_u25)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, classList__OOZOOZsrcZtiaraZbuilder_u35)(NimStringV2* classes_p0, NI classes_p0Len_0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZappZviewsZhome_u176)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q, mergeAttrs__OOZOOZsrcZtiaraZcomponentsZutils_u5)(tyTuple__UV3llMMYFckfui8YMBuUZA* baseAttrs_p0, NI baseAttrs_p0Len_0, tySequence__4eQHGndY6XBYpFOH09apV8Q extraAttrs_p1);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__Wlmkgrssb1vBcJ9buY9a35eA_2 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_3 = { 14 | NIM_STRLIT_FLAG, "tiara-carousel" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_4 = {14, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_3};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_5 = { 7 | NIM_STRLIT_FLAG, "article" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_6 = {7, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_5};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_8 = { 5 | NIM_STRLIT_FLAG, "class" };
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_9 = { 14 | NIM_STRLIT_FLAG, "carousel-slide" };
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_10 = { 25 | NIM_STRLIT_FLAG, "data-tiara-carousel-slide" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_11 = {25, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_10};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_12 = { 11 | NIM_STRLIT_FLAG, "aria-hidden" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_13 = {11, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_12};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_14 = { 5 | NIM_STRLIT_FLAG, "false" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_15 = {5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_14};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_16 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_17 = {4, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_16};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_18 = {7, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_5};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_19 = { 8 | NIM_STRLIT_FLAG, "No items" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_20 = {8, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_19};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_21 = { 1 | NIM_STRLIT_FLAG, "p" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_22 = {1, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_21};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_24 = { 1 | NIM_STRLIT_FLAG, "0" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_26 = { 3 | NIM_STRLIT_FLAG, "div" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_27 = {3, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_26};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_29 = { 14 | NIM_STRLIT_FLAG, "carousel-track" };
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_31 = { 25 | NIM_STRLIT_FLAG, "data-tiara-carousel-track" };
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_32 = { 0 | NIM_STRLIT_FLAG, "" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_34 = { 5 | NIM_STRLIT_FLAG, "style" };
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_35 = { 26 | NIM_STRLIT_FLAG, "transform: translateX(0%);" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_36 = { 6 | NIM_STRLIT_FLAG, "button" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_37 = {6, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_36};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_38 = { 3 | NIM_STRLIT_FLAG, "\342\200\271" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_39 = {3, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_38};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_41 = { 4 | NIM_STRLIT_FLAG, "type" };
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_43 = { 30 | NIM_STRLIT_FLAG, "carousel-nav carousel-nav-prev" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_45 = { 10 | NIM_STRLIT_FLAG, "aria-label" };
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_46 = { 14 | NIM_STRLIT_FLAG, "Previous slide" };
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_48 = { 26 | NIM_STRLIT_FLAG, "data-tiara-carousel-action" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_49 = { 4 | NIM_STRLIT_FLAG, "prev" };
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_50 = { 26 | NIM_STRLIT_FLAG, "data-tiara-carousel-target" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_51 = {26, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_50};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_52 = {6, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_36};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_53 = { 3 | NIM_STRLIT_FLAG, "\342\200\272" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_54 = {3, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_53};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_56 = { 30 | NIM_STRLIT_FLAG, "carousel-nav carousel-nav-next" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_58 = { 10 | NIM_STRLIT_FLAG, "Next slide" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_60 = { 4 | NIM_STRLIT_FLAG, "next" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_61 = {26, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_50};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_62 = {6, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_36};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_63 = {0, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_32};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_64 = {5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_8};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_65 = { 18 | NIM_STRLIT_FLAG, "carousel-indicator" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_66 = {18, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_65};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_67 = { 9 | NIM_STRLIT_FLAG, "is-active" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_68 = {9, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_67};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_69 = {0, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_32};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_71 = { 2 | NIM_STRLIT_FLAG, "go" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_72 = {26, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_50};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_73 = { 22 | NIM_STRLIT_FLAG, "data-tiara-carousel-go" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_74 = {22, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_73};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_75 = { 29 | NIM_STRLIT_FLAG, "data-tiara-carousel-indicator" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_76 = {29, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_75};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_77 = {10, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_45};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_78 = { 12 | NIM_STRLIT_FLAG, "Go to slide " };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_79 = {12, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_78};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_81 = { 12 | NIM_STRLIT_FLAG, "aria-current" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_82 = {12, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_81};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_83 = {4, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_16};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_84 = {5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_14};
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_86 = {3, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_26};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_88 = { 19 | NIM_STRLIT_FLAG, "carousel-indicators" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_89 = { 7 | NIM_STRLIT_FLAG, "section" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_90 = {7, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_89};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_91 = { 2 | NIM_STRLIT_FLAG, "id" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_92 = {2, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_91};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_94 = { 8 | NIM_STRLIT_FLAG, "carousel" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_96 = { 10 | NIM_STRLIT_FLAG, "data-tiara" };
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_98 = { 25 | NIM_STRLIT_FLAG, "data-tiara-carousel-index" };
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__Wlmkgrssb1vBcJ9buY9a35eA_99 = { 24 | NIM_STRLIT_FLAG, "data-tiara-carousel-size" };
static const NimStringV2 TM__Wlmkgrssb1vBcJ9buY9a35eA_100 = {24, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_99};
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_7 = {{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_8},
{14, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_9}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_23 = {{25, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_10},
{1, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_24}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_25 = {{11, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_12},
{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_14}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_28 = {{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_8},
{14, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_29}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_30 = {{25, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_31},
{0, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_32}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_33 = {{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_34},
{26, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_35}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_40 = {{4, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_41},
{6, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_36}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_42 = {{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_8},
{30, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_43}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_44 = {{10, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_45},
{14, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_46}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_47 = {{26, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_48},
{4, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_49}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_55 = {{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_8},
{30, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_56}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_57 = {{10, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_45},
{10, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_58}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_59 = {{26, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_48},
{4, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_60}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_70 = {{26, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_48},
{2, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_71}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_87 = {{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_8},
{19, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_88}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_93 = {{5, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_8},
{8, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_94}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_95 = {{10, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_96},
{8, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_94}}
;
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__Wlmkgrssb1vBcJ9buY9a35eA_97 = {{25, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_98},
{1, (NimStrPayload*)&TM__Wlmkgrssb1vBcJ9buY9a35eA_24}}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(NimStringV2, textNode__OOZOOZsrcZtiaraZbuilder_u32)(NimStringV2 value_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("textNode", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(30, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");	result = escapeHtml__OOZOOZsrcZtiaraZbuilder_u28(value_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, rawHtml__OOZOOZsrcZtiaraZbuilder_u25)(NimStringV2 value_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	nimfr_("rawHtml", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/builder.nim");
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(10);	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD_ = eqdup___system_u2728(value_p0);
	result = colontmpD_;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, carousel__OOZOOZexamplesZpreview_u3716)(NimStringV2 id_p1, NimStringV2* items_p2, NI items_p2Len_0, NIM_BOOL showIndicators_p3, tySequence__4eQHGndY6XBYpFOH09apV8Q attrs_p4) {
	NimStringV2 result;
	NimStringV2 safeId_1;
	NimStringV2 colontmpD_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ slides_1;
	NimStringV2 track_1;
	NimStringV2 colontmpD__2;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__3;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ bodySegments_1;
	NimStringV2 colontmpD__4;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__5;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__6;
	NimStringV2 T1_;
	NI size_1;
	NI T24_;
	NimStringV2 blitTmp_3;
	NimStringV2 blitTmp_6;
	NimStringV2 T55_;
NIM_BOOL* nimErr_;
	nimfr_("carousel", "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	safeId_1.len = 0; safeId_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	slides_1.len = 0; slides_1.p = NIM_NIL;
	track_1.len = 0; track_1.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	bodySegments_1.len = 0; bodySegments_1.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	nimlf_(13, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");	{
		colontmpD_ = nsuStrip(id_p1, NIM_TRUE, NIM_TRUE, TM__Wlmkgrssb1vBcJ9buY9a35eA_2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(colontmpD_.len == ((NI)0))) goto LA4_;
		nimln_(12);		nimln_(14);		safeId_1 = TM__Wlmkgrssb1vBcJ9buY9a35eA_4;
	}
	goto LA2_;
LA4_: ;
	{
		nimln_(12);		nimln_(16);		safeId_1 = normalizeDomId__OOZOOZsrcZtiaraZcomponentsZutils_u139(id_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA2_: ;
	nimln_(18);	slides_1.len = 0; slides_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 item_1;
		NI idx_1;
		NI i_1;
		item_1.len = 0; item_1.p = NIM_NIL;
		idx_1 = (NI)0;
		nimlf_(148, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(149);			while (1) {
				NimStringV2 colontmpD__7;
				NimStringV2 colontmpD__8;
				tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__9;
				NimStringV2 T10_;
				NimStringV2 T16_;
				if (!(i_1 < items_p2Len_0)) goto LA9;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
				colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
				nimlf_(19, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");				idx_1 = i_1;
				if (i_1 < 0 || i_1 >= items_p2Len_0){ raiseIndexError2(i_1,items_p2Len_0-1); goto BeforeRet_;
				}
				item_1 = items_p2[i_1];
				nimln_(20);				nimln_(21);				nimln_(24);				colontmpD__9.len = 3; colontmpD__9.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(3, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
				colontmpD__9.p->data[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_7;
				colontmpD__9.p->data[1].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_11;
				nimln_(26);				T10_.len = 0; T10_.p = NIM_NIL;
				T10_ = dollar___systemZdollars_u14(idx_1);
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T10_); goto BeforeRet_;}
				colontmpD__9.p->data[1].Field1 = T10_;
				colontmpD__9.p->data[2].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_13;
				nimln_(27);				{
					NimStringV2 blitTmp_1;
					if (!(idx_1 == ((NI)0))) goto LA13_;
					colontmpD__7 = TM__Wlmkgrssb1vBcJ9buY9a35eA_15;
					blitTmp_1 = colontmpD__7;
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					eqwasMoved___system_u2722((&colontmpD__7));
					colontmpD__9.p->data[2].Field1 = blitTmp_1;
				}
				goto LA11_;
LA13_: ;
				{
					NimStringV2 blitTmp_2;
					nimlf_(27, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");					colontmpD__8 = TM__Wlmkgrssb1vBcJ9buY9a35eA_17;
					blitTmp_2 = colontmpD__8;
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					eqwasMoved___system_u2722((&colontmpD__8));
					colontmpD__9.p->data[2].Field1 = blitTmp_2;
				}
LA11_: ;
				nimlf_(21, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");				T16_.len = 0; T16_.p = NIM_NIL;
				T16_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_6, item_1, ((colontmpD__9).p) ? (colontmpD__9.p->data) : NIM_NIL, colontmpD__9.len);
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T16_); goto BeforeRet_;}
				nimln_(20);				add__OOZsrcZappZviewsZhome_u57((&slides_1), T16_);
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");				eqdestroy___stdZenvvars_u103(colontmpD__9);
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
				if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
			} LA9: ;
		}
	}
	nimlf_(32, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");	{
		NI T19_;
		NimStringV2 colontmpD__10;
		tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__11;
		tySequence__4eQHGndY6XBYpFOH09apV8Q T22_;
		NimStringV2 T23_;
		T19_ = slides_1.len;
		if (!(T19_ == ((NI)0))) goto LA20_;
		colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
		colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
		nimln_(33);		nimln_(34);		nimln_(36);		T22_.len = 0; T22_.p = NIM_NIL;
		T22_.len = 0; T22_.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(0, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
		colontmpD__10 = text__OOZOOZexamplesZpreview_u57(TM__Wlmkgrssb1vBcJ9buY9a35eA_20, TM__Wlmkgrssb1vBcJ9buY9a35eA_22, T22_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(37);		colontmpD__11.len = 3; colontmpD__11.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(3, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
		colontmpD__11.p->data[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_7;
		colontmpD__11.p->data[1] = TM__Wlmkgrssb1vBcJ9buY9a35eA_23;
		colontmpD__11.p->data[2] = TM__Wlmkgrssb1vBcJ9buY9a35eA_25;
		nimln_(34);		T23_.len = 0; T23_.p = NIM_NIL;
		T23_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_18, colontmpD__10, ((colontmpD__11).p) ? (colontmpD__11.p->data) : NIM_NIL, colontmpD__11.len);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T23_); goto BeforeRet_;}
		nimln_(33);		add__OOZsrcZappZviewsZhome_u57((&slides_1), T23_);
		nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");		eqdestroy___stdZenvvars_u103(colontmpD__11);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
	}
LA20_: ;
	nimlf_(45, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");	T24_ = slides_1.len;
	size_1 = T24_;
	nimln_(46);	nimln_(48);	colontmpD__2 = joinHtml__OOZOOZsrcZtiaraZbuilder_u575(((slides_1).p) ? (slides_1.p->data) : NIM_NIL, slides_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(49);	colontmpD__3.len = 3; colontmpD__3.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(3, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
	colontmpD__3.p->data[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_28;
	colontmpD__3.p->data[1] = TM__Wlmkgrssb1vBcJ9buY9a35eA_30;
	colontmpD__3.p->data[2] = TM__Wlmkgrssb1vBcJ9buY9a35eA_33;
	nimln_(46);	track_1 = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_27, colontmpD__2, ((colontmpD__3).p) ? (colontmpD__3.p->data) : NIM_NIL, colontmpD__3.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(56);	bodySegments_1.len = 1; bodySegments_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	blitTmp_3 = track_1;
	bodySegments_1.p->data[0] = blitTmp_3;
	nimln_(58);	{
		NimStringV2 colontmpD__12;
		NimStringV2 colontmpD__13;
		tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__14;
		NimStringV2 colontmpD__15;
		NimStringV2 colontmpD__16;
		tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__17;
		NimStringV2 T29_;
		NimStringV2 T30_;
		if (!(((NI)1) < size_1)) goto LA27_;
		colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
		colontmpD__13.len = 0; colontmpD__13.p = NIM_NIL;
		colontmpD__14.len = 0; colontmpD__14.p = NIM_NIL;
		colontmpD__15.len = 0; colontmpD__15.p = NIM_NIL;
		colontmpD__16.len = 0; colontmpD__16.p = NIM_NIL;
		colontmpD__17.len = 0; colontmpD__17.p = NIM_NIL;
		nimln_(59);		nimln_(60);		nimln_(62);		colontmpD__12 = textNode__OOZOOZsrcZtiaraZbuilder_u32(TM__Wlmkgrssb1vBcJ9buY9a35eA_39);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(63);		colontmpD__14.len = 5; colontmpD__14.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(5, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
		colontmpD__14.p->data[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_40;
		colontmpD__14.p->data[1] = TM__Wlmkgrssb1vBcJ9buY9a35eA_42;
		colontmpD__14.p->data[2] = TM__Wlmkgrssb1vBcJ9buY9a35eA_44;
		colontmpD__14.p->data[3] = TM__Wlmkgrssb1vBcJ9buY9a35eA_47;
		colontmpD__14.p->data[4].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_51;
		nimln_(68);		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		colontmpD__13 = eqdup___system_u2728(safeId_1);
		colontmpD__14.p->data[4].Field1 = colontmpD__13;
		nimlf_(60, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");		T29_.len = 0; T29_.p = NIM_NIL;
		T29_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_37, colontmpD__12, ((colontmpD__14).p) ? (colontmpD__14.p->data) : NIM_NIL, colontmpD__14.len);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T29_); goto BeforeRet_;}
		nimln_(59);		add__OOZsrcZappZviewsZhome_u57((&bodySegments_1), T29_);
		nimln_(73);		nimln_(74);		nimln_(76);		colontmpD__15 = textNode__OOZOOZsrcZtiaraZbuilder_u32(TM__Wlmkgrssb1vBcJ9buY9a35eA_54);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(77);		colontmpD__17.len = 5; colontmpD__17.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(5, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
		colontmpD__17.p->data[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_40;
		colontmpD__17.p->data[1] = TM__Wlmkgrssb1vBcJ9buY9a35eA_55;
		colontmpD__17.p->data[2] = TM__Wlmkgrssb1vBcJ9buY9a35eA_57;
		colontmpD__17.p->data[3] = TM__Wlmkgrssb1vBcJ9buY9a35eA_59;
		colontmpD__17.p->data[4].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_61;
		nimln_(82);		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		colontmpD__16 = eqdup___system_u2728(safeId_1);
		colontmpD__17.p->data[4].Field1 = colontmpD__16;
		nimlf_(74, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");		T30_.len = 0; T30_.p = NIM_NIL;
		T30_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_52, colontmpD__15, ((colontmpD__17).p) ? (colontmpD__17.p->data) : NIM_NIL, colontmpD__17.len);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T30_); goto BeforeRet_;}
		nimln_(73);		add__OOZsrcZappZviewsZhome_u57((&bodySegments_1), T30_);
		nimln_(87);		{
			tySequence__sM4lkSb7zS6F7OVMvW9cffQ indicatorNodes_1;
			NimStringV2 colontmpD__18;
			tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__19;
			NimStringV2 T54_;
			if (!showIndicators_p3) goto LA33_;
			indicatorNodes_1.len = 0; indicatorNodes_1.p = NIM_NIL;
			colontmpD__18.len = 0; colontmpD__18.p = NIM_NIL;
			colontmpD__19.len = 0; colontmpD__19.p = NIM_NIL;
			nimln_(88);			indicatorNodes_1.len = 0; indicatorNodes_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
			{
				NI idx_2;
				NI i_2;
				idx_2 = (NI)0;
				nimlf_(128, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				i_2 = ((NI)0);
				{
					nimln_(129);					while (1) {
						NimStringV2 colontmpD__20;
						NimStringV2 colontmpD__21;
						NimStringV2 colontmpD__22;
						NimStringV2 colontmpD__23;
						NimStringV2 colontmpD__24;
						NimStringV2 colontmpD__25;
						NimStringV2 colontmpD__26;
						tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD__27;
						tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T38_;
						NimStringV2 T44_;
						NimStringV2 T45_;
						NimStringV2 T46_;
						NimStringV2 T47_;
						NI TM__Wlmkgrssb1vBcJ9buY9a35eA_80;
						NimStringV2 T53_;
						NI TM__Wlmkgrssb1vBcJ9buY9a35eA_85;
						if (!(i_2 < size_1)) goto LA37;
						colontmpD__20.len = 0; colontmpD__20.p = NIM_NIL;
						colontmpD__21.len = 0; colontmpD__21.p = NIM_NIL;
						colontmpD__22.len = 0; colontmpD__22.p = NIM_NIL;
						colontmpD__23.len = 0; colontmpD__23.p = NIM_NIL;
						colontmpD__24.len = 0; colontmpD__24.p = NIM_NIL;
						colontmpD__25.len = 0; colontmpD__25.p = NIM_NIL;
						colontmpD__26.len = 0; colontmpD__26.p = NIM_NIL;
						colontmpD__27.len = 0; colontmpD__27.p = NIM_NIL;
						nimlf_(89, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");						idx_2 = i_2;
						nimln_(90);						nimln_(91);						nimln_(93);						colontmpD__20 = rawHtml__OOZOOZsrcZtiaraZbuilder_u25(TM__Wlmkgrssb1vBcJ9buY9a35eA_63);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimln_(94);						colontmpD__27.len = 8; colontmpD__27.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(8, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
						colontmpD__27.p->data[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_40;
						colontmpD__27.p->data[1].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_64;
						nimln_(96);						T38_[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_66;
						{
							if (!(idx_2 == ((NI)0))) goto LA41_;
							colontmpD__21 = TM__Wlmkgrssb1vBcJ9buY9a35eA_68;
							T38_[1] = colontmpD__21;
						}
						goto LA39_;
LA41_: ;
						{
							colontmpD__22 = TM__Wlmkgrssb1vBcJ9buY9a35eA_69;
							T38_[1] = colontmpD__22;
						}
LA39_: ;
						T44_.len = 0; T44_.p = NIM_NIL;
						T44_ = classList__OOZOOZsrcZtiaraZbuilder_u35(T38_, 2);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T44_); goto BeforeRet_;}
						colontmpD__27.p->data[1].Field1 = T44_;
						colontmpD__27.p->data[2] = TM__Wlmkgrssb1vBcJ9buY9a35eA_70;
						colontmpD__27.p->data[3].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_72;
						nimln_(98);						nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");						colontmpD__23 = eqdup___system_u2728(safeId_1);
						colontmpD__27.p->data[3].Field1 = colontmpD__23;
						colontmpD__27.p->data[4].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_74;
						nimlf_(99, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");						T45_.len = 0; T45_.p = NIM_NIL;
						T45_ = dollar___systemZdollars_u14(idx_2);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T45_); goto BeforeRet_;}
						colontmpD__27.p->data[4].Field1 = T45_;
						colontmpD__27.p->data[5].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_76;
						nimln_(100);						T46_.len = 0; T46_.p = NIM_NIL;
						T46_ = dollar___systemZdollars_u14(idx_2);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T46_); goto BeforeRet_;}
						colontmpD__27.p->data[5].Field1 = T46_;
						colontmpD__27.p->data[6].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_77;
						nimln_(101);						T47_.len = 0; T47_.p = NIM_NIL;
						if (nimAddInt(idx_2, ((NI)1), &TM__Wlmkgrssb1vBcJ9buY9a35eA_80)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD__24 = dollar___systemZdollars_u14((NI)(TM__Wlmkgrssb1vBcJ9buY9a35eA_80));
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						T47_ = rawNewString(colontmpD__24.len + 12);
appendString((&T47_), TM__Wlmkgrssb1vBcJ9buY9a35eA_79);
appendString((&T47_), colontmpD__24);
						colontmpD__27.p->data[6].Field1 = T47_;
						colontmpD__27.p->data[7].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_82;
						nimln_(102);						{
							NimStringV2 blitTmp_4;
							if (!(idx_2 == ((NI)0))) goto LA50_;
							colontmpD__25 = TM__Wlmkgrssb1vBcJ9buY9a35eA_83;
							blitTmp_4 = colontmpD__25;
							nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");							eqwasMoved___system_u2722((&colontmpD__25));
							colontmpD__27.p->data[7].Field1 = blitTmp_4;
						}
						goto LA48_;
LA50_: ;
						{
							NimStringV2 blitTmp_5;
							nimlf_(102, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");							colontmpD__26 = TM__Wlmkgrssb1vBcJ9buY9a35eA_84;
							blitTmp_5 = colontmpD__26;
							nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");							eqwasMoved___system_u2722((&colontmpD__26));
							colontmpD__27.p->data[7].Field1 = blitTmp_5;
						}
LA48_: ;
						nimlf_(91, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");						T53_.len = 0; T53_.p = NIM_NIL;
						T53_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_62, colontmpD__20, ((colontmpD__27).p) ? (colontmpD__27.p->data) : NIM_NIL, colontmpD__27.len);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T53_); goto BeforeRet_;}
						nimln_(90);						add__OOZsrcZappZviewsZhome_u57((&indicatorNodes_1), T53_);
						nimlf_(131, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__Wlmkgrssb1vBcJ9buY9a35eA_85)) { raiseOverflow(); goto BeforeRet_;
						};
						i_2 = (NI)(TM__Wlmkgrssb1vBcJ9buY9a35eA_85);
						nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");						eqdestroy___stdZenvvars_u103(colontmpD__27);
						nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");						if (colontmpD__26.p && !(colontmpD__26.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__26.p);
}
						if (colontmpD__25.p && !(colontmpD__25.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__25.p);
}
						if (colontmpD__24.p && !(colontmpD__24.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__24.p);
}
						if (colontmpD__22.p && !(colontmpD__22.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__22.p);
}
						if (colontmpD__21.p && !(colontmpD__21.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__21.p);
}
						if (colontmpD__20.p && !(colontmpD__20.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__20.p);
}
					} LA37: ;
				}
			}
			nimlf_(107, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");			colontmpD__18 = joinHtml__OOZOOZsrcZtiaraZbuilder_u575(((indicatorNodes_1).p) ? (indicatorNodes_1.p->data) : NIM_NIL, indicatorNodes_1.len);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			colontmpD__19.len = 1; colontmpD__19.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(1, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
			colontmpD__19.p->data[0] = TM__Wlmkgrssb1vBcJ9buY9a35eA_87;
			T54_.len = 0; T54_.p = NIM_NIL;
			T54_ = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_86, colontmpD__18, ((colontmpD__19).p) ? (colontmpD__19.p->data) : NIM_NIL, colontmpD__19.len);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T54_); goto BeforeRet_;}
			add__OOZsrcZappZviewsZhome_u57((&bodySegments_1), T54_);
			nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");			eqdestroy___stdZenvvars_u103(colontmpD__19);
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (colontmpD__18.p && !(colontmpD__18.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__18.p);
}
			nimlf_(22, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/navbar.nim");			eqdestroy___OOZsrcZappZviewsZhome_u176(indicatorNodes_1);
		}
LA33_: ;
		nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");		eqdestroy___stdZenvvars_u103(colontmpD__17);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__15.p && !(colontmpD__15.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__15.p);
}
		nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");		eqdestroy___stdZenvvars_u103(colontmpD__14);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
	}
LA27_: ;
	nimlf_(5, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/carousel.nim");	nimln_(109);	nimln_(111);	colontmpD__4 = joinHtml__OOZOOZsrcZtiaraZbuilder_u575(((bodySegments_1).p) ? (bodySegments_1.p->data) : NIM_NIL, bodySegments_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(112);	nimln_(113);	colontmpD__5.len = 5; colontmpD__5.p = (tySequence__4eQHGndY6XBYpFOH09apV8Q_Content*) newSeqPayload(5, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA), NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA));
	colontmpD__5.p->data[0].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_92;
	nimln_(114);	blitTmp_6 = safeId_1;
	colontmpD__5.p->data[0].Field1 = blitTmp_6;
	colontmpD__5.p->data[1] = TM__Wlmkgrssb1vBcJ9buY9a35eA_93;
	colontmpD__5.p->data[2] = TM__Wlmkgrssb1vBcJ9buY9a35eA_95;
	colontmpD__5.p->data[3] = TM__Wlmkgrssb1vBcJ9buY9a35eA_97;
	colontmpD__5.p->data[4].Field0 = TM__Wlmkgrssb1vBcJ9buY9a35eA_100;
	nimln_(118);	T55_.len = 0; T55_.p = NIM_NIL;
	T55_ = dollar___systemZdollars_u14(size_1);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T55_); goto BeforeRet_;}
	colontmpD__5.p->data[4].Field1 = T55_;
	nimln_(112);	colontmpD__6 = mergeAttrs__OOZOOZsrcZtiaraZcomponentsZutils_u5(((colontmpD__5).p) ? (colontmpD__5.p->data) : NIM_NIL, colontmpD__5.len, attrs_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	result = el__OOZOOZsrcZtiaraZbuilder_u563(TM__Wlmkgrssb1vBcJ9buY9a35eA_90, colontmpD__4, ((colontmpD__6).p) ? (colontmpD__6.p->data) : NIM_NIL, colontmpD__6.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");	eqdestroy___stdZenvvars_u103(colontmpD__6);
	eqdestroy___stdZenvvars_u103(colontmpD__5);
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
	nimlf_(22, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/navbar.nim");	eqdestroy___OOZsrcZappZviewsZhome_u176(bodySegments_1);
	nimlf_(220, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/envvars.nim");	eqdestroy___stdZenvvars_u103(colontmpD__3);
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	nimlf_(22, "/Users/nakagawa_shota/repo/valit/tiara/src/tiara/components/navbar.nim");	eqdestroy___OOZsrcZappZviewsZhome_u176(slides_1);
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
